### ISSUE TITLE
Antares Autotune 8.1 Crashes Juce Plugin Host

### ISSUE THREAD

**Issue by audiostrom** [WeAreROLI/JUCE#113]
On latest tip, compiled the plugin host demo
Running Windows 10 x64
64 bit version of host.
VST3 version of plugin (Only available)

[Link to plugin trial](http://www.antarestech.com/products/detail.php?product=Auto-Tune_8_66)

It crashes during scan, and it can not be run under debugger.
I guess Antares will have to be contacted by Juce developers.
The issue is confirmed by multiple end users of our host software.

[Link to forum thread:](https://forum.juce.com/t/antares-autotune-8-1/19336)

**Comment by hogliux** [comment]
We are in contact with Antares and they are looking to fix this problem with their next iteration of their iLok copy protection integration code. In the meantime, you can use the workaround described in [this forum post](https://forum.juce.com/t/antares-autotune-8-1-crashes-demo-host).
