### ISSUE TITLE
Issue with SVG fill (+ partial fix patch)

### ISSUE THREAD

**Issue by LucianLandry** [WeAreROLI/JUCE#114]
Hello, I'm having trouble displaying [this SVG image](https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces#/media/File:Chess_ndt45.svg)
from Juce (I tried git snapshots from 2016-10-04 and 2016-10-08).  The image appears to lack fill in certain areas.

Expected behavior: Image should look like it does when browsing the above link from a standard web browser (firefox, chrome, etc.)

Observed behavior: (attached png from Juce Demo to show observed behavior)
![knightbad](https://cloud.githubusercontent.com/assets/17329331/19216089/3b941b98-8d75-11e6-80ee-f120411c3520.png)

To reproduce: load the SVG into icons.zip and re-generate the Demo's BinaryData, then run the Demo and try the SVG demo.

OS used: Linux 64-bit (Debian Jessie)

Root cause is probably a failure to adhere to the SVG Tiny 1.2 spec, section 11.3:
"Open subpaths must be filled by performing the fill operation as if an additional "closepath" command were added to the path to connect the last point of the subpath with the first point of the subpath."

A partial fix (good enough to solve my issue, but I think I only addressed top-level path fill, not subpath fill) is attached as a patchfile against the 20161008 snapshot. I disclaim all ownership of the patch, assuming copyright is an issue.
[gitpatch.txt](https://github.com/julianstorer/JUCE/files/517949/gitpatch.txt)

**Comment by julianstorer** [comment]
Not sure when this was fixed, but it seems to work OK in the latest build.

**Comment by LucianLandry** [comment]
Sorry, but a preliminary check makes me think this is still broken with 5.0.2.  I'll write another issue in a day or so.

**Comment by julianstorer** [comment]
It loads fine in the latest projucer.

And the stuff about adding an "implicit close" to the Path class really wouldn't be an acceptable fix - it's totally unclear to me what that even means, and I don't think an SVG parsing problem justifies a change to such a fundamental and unrelated class.
