### ISSUE TITLE
Projucer - Illegal instruction, core dumped

### ISSUE THREAD

**Issue by lukeoftheaura** [WeAreROLI/JUCE#115]
I've downloaded the latest version of JUCE from the website, and I have tried to run projucer, and I get this when I try to run it:
`[1]    1671 illegal hardware instruction (core dumped)  ./Projucer`
I'm running antergos linux 64-bit, if that helps.

**Comment by billic** [comment]
There are some special CPU instructions in official projucer builds. Looks like juce team build it with core i7 optimization [look here](https://forum.juce.com/t/unable-to-run-projucer-on-ubuntu-15-10/15874/19).

There is an other way (it can be found in same link). You should git clone latest juce release and build it by yourself. Probably you should also satisfy some dependencies. You can found something like actual list [here](https://forum.juce.com/t/list-of-juce-dependencies-under-linux/15121/19)
