### ISSUE TITLE
Xenial UNITY display issue with full-screen

### ISSUE THREAD

**Issue by Lewiscowles1986** [WeAreROLI/JUCE#116]
1) Steps to reproduce

``` shell
cd ~/
git clone https://github.com/julianstorer/JUCE
cd JUCE/Examples/HelloWorld/Builds/Linux
make
cd build
./HelloWorld
```

2) Expectations
- App launches :+1: 
- Application makes some sense :+1: 
- Window controls behave consistently with OS norms :cry: 

![image](https://cloud.githubusercontent.com/assets/2605791/19311747/8765a716-9087-11e6-9776-972150cd04fb.png)

> Maximizing the window takes the entire screen size, which seems to interfere with unity.
- Presentation of window controls is well designed, or conforms to OS standards (nice to have, complex issue as is subjective) :confused: 

![image](https://cloud.githubusercontent.com/assets/2605791/19312360/ef43ef3a-9089-11e6-8af6-a734f2c8d737.png)

> Note the window handle icons seem to be slightly non-uniformly aligned with close having a larger gap between than other handles.

3) Ubuntu Xenial 16.04 (All updates applied)
4) x64 architecture

> Output of `uname -a` 
> 
> ``` shell
> Linux lewis-HP-ENVY-17-Notebook-PC 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> ```

5) N/A
6) N/A
7) N/A
### Juice version

![image](https://cloud.githubusercontent.com/assets/2605791/19311728/76ae04f4-9087-11e6-9662-6f25e82e1caf.png)

**Comment by ed95** [comment]
Looks like this has been fixed as of JUCE 5.4.5. Feel free to re-open this issue if not.
