### ISSUE TITLE
NDK-bundle on Windows only detects up to version 11c

### ISSUE THREAD

**Issue by ghost** [WeAreROLI/JUCE#117]
Please include:

1) On clean system, after downloading the ndk from android-studio (version 13, right now) it wont detect it. Also tried with version 12 and was a no go.

Version 11C and belowwill detect it ok

  2) In the tools preferece for ndk-bundle its not detected in version 12 and above
  3) Windows, tested 7,8,10
  4) 64-bit

**Comment by ed95** [comment]
Looks like this has been fixed as of JUCE 5.4.5. Feel free to re-open this issue if not.
