### ISSUE TITLE
Standalone plugin target does not support plugins with more than 2 channel outputs (on most hardware)

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [WeAreROLI/JUCE#118]
1) Create a new audio plugin project using the Jucer tool, set the input channels to 2 and output to 8
  2) The audio unit project is created and works as expected in Ableton, however the standalone player target has an assert when running.
  3) MAC OSX 10.12
  4) 64-bit
  5)  jassert (processorToPlay->getTotalNumOutputChannels() == numOutputChans); in AudioProcessorPlayer
  6) AU
  7) N/A

This is due to the device output channels (2) not matching the plugin output channels (8). Therefore the standalone test environment only supports testing plugins with the same number of channels as device channels.

**Comment by ed95** [comment]
Looks like this has been fixed as of JUCE 5.4.5. Feel free to re-open this issue if not.
