### ISSUE TITLE
anotherInstanceStarted don't gets called on MacOS Sierra...

### ISSUE THREAD

**Issue by esurharun** [WeAreROLI/JUCE#122]
I found a bug on MacOS Sierra x64 on JUCE 4.2.4, 

Even though moreThanOneInstanceAllowed returns false, anotherInstanceStarted was getting called.

But on MacOS Sierra it does not work.

**Comment by esurharun** [comment]
Ok. Fixed by updating JUCE sources...

You should change juce_mac_messagemanager.mm line 81 from 
```Objective-c
  [[NSDistributedNotificationCenter defaultCenter] removeObserver: delegate
                                                                       name: getBroadcastEventName()
                                                                     object: nil];
```

to 

```Objective-c
[[NSDistributedNotificationCenter defaultCenter] addObserver: delegate
															selector: @selector (broadcastMessageCallback:)
																name: getBroadcastEventName()
															  object: nil
														suspensionBehavior:NSNotificationSuspensionBehaviorDeliverImmediately];
```

otherwise it waits for and event on the other process and sets default to NSNotificationSuspensionBehaviorCoalesce.

**Comment by julianstorer** [comment]
Thanks! That does seem to work, I'll sort it out. (And sorry - only just saw this report months after you posted it!)
