### ISSUE TITLE
InputStream::readIntoMemoryBlock() returns size_t but other InputStream methods return int64

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#131]
`readIntoMemoryBlock ()` returns a `size_t`, but all other methods in `InputStream` that return a number of bytes, return an `int64`. E.g. 

```
virtual size_t readIntoMemoryBlock (MemoryBlock& destBlock,
                                        ssize_t maxNumBytesToRead = -1);
virtual int64 getTotalLength() = 0;
```

This means that, e.g. `getTotalLength()`  can't faithfully return the actual total length in bytes, if the number of bytes read is greater than LONG_MAX

**Comment by julianstorer** [comment]
It's reading into a MemoryBlock, so it can't possibly read more than size_t bytes, since that would require it to allocate more memory than the program is allowed.
