### ISSUE TITLE
Setting Project Name in Projucer doesn't update Target Name in Xcode

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#132]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

- Create a Projucer project, e.g. a console app called "My App"
- Save Project and Open in IDE... Xcode(MacOSX)
- See the target name is "My App"
- Change the Project Name  to e.g. "Foo App"
- Save Project and Open in IDE... Xcode(MacOSX)

  2) the expected behaviour

- The target name is changed to "Foo App"

2a) the actual behaviour

- The target name is still "My App"

  3) the operating system

Mac OS X 10.11

  4) the architecture (32-bit or 64-bit)

64-bit

Note: there appears to be no way to make the target name change in Xcode from the Projucer. The only way I could change it is by editing the `targetName` property in .jucer XML:

` <EXPORTFORMATS>
    <XCODE_MAC targetFolder="Builds/MacOSX">
      <CONFIGURATIONS>
          <CONFIGURATION name="Debug" isDebug="1" optimisation="1" targetName="ODE_MAC targetFolder="Builds/MacOSX">
              <CONFIGURATIONS>
                  <CONFIGURATION name="Debug" isDebug="1" optimisation="1" targetName="Foo App"/>                  <CONFIGURATION name="Release" isDebug="0" optimisation="3" targetName="Foo App"</CONFIGURATIONS></CONFIGURATION>
        <CONFIGURATION name="Release" isDebug="0" optimisation="3" targetName="Foo App"/>
`

**Comment by notinflight** [comment]
I'm having the same issue, where is the .jucer XML file located?

**Comment by ed95** [comment]
I've just tested this with the steps you posted and I believe this has been fixed - feel free to open the issue again if it hasn't though.
