### ISSUE TITLE
AudioProcessorValueTreeState: valueToTextFunction, textToValueFunction

### ISSUE THREAD

**Issue by johanneskares** [WeAreROLI/JUCE#134]
1) **steps**: create a plugin with the AudioProcessorValueTeeState. use createAndAddParameter, but don't specify a valueToTextFunction or textToValueFunction
  2) **expected behavior**: the plugins shows an unnormalised Value in its parameter list (any DAW, but most easily visble in the Plugin Host). For example I added a parameter 0% - 100% and the hosts show it as 0.0% - 1.0%
  3) **OS**: any
  4) **architecture** any
  5) **Stack Trace** not applicable
  6) **format** VST, VST3, AU
  7) **DAWs tested**: Plugin-Host, Ableton, Reaper

**Comment by tpoole** [comment]
Fixed in JUCE 5.4.1.
