### ISSUE TITLE
AudioProcessorValueTreeState: VST3 doesn't use interval value of Parameter

### ISSUE THREAD

**Issue by johanneskares** [WeAreROLI/JUCE#135]
1) **steps**: create a plugin with the AudioProcessorValueTeeState. use createAndAddParameter and specify an interval value with the NormelisableRange
  2) **expected behavior**: The DAW uses the interval value and the value jumps between the different intervals, but with VST3 all values are possible. It's working as expected with VST and AU but not with VST3
  3) **OS**: any
  4) **architecture** any
  5) **Stack Trace** not applicable
  6) **format** VST3
  7) **DAWs tested**: Plugin-Host, Reaper

**Comment by francoisbecker** [comment]
With VST3 if you want the parameter to be ramped in the automation, according to the VST3 doc the number of steps is to be set to 0 (not yet done in JUCE), so you'll not be able to have "jumps" of value parameters (from the host perspective) between the plug-in-configured number of steps.

**Comment by tpoole** [comment]
Fixed in JUCE 5.4.1.
