### ISSUE TITLE
FileHelpers needs renaming to MacFileHelpers in juce_mac_Files.mm

### ISSUE THREAD

**Issue by adamski** [WeAreROLI/JUCE#137]
Commit 2952b52f88966a20535b54fa13da9ec6bc2be4dd breaks my iOS project, I had to rename FileHelpers to MacFileHelpers also in juce_mac_Files.mm

**Comment by julianstorer** [comment]
I'm guessing this has been fixed at some point since this report, as the namespaces all look correct now.
