### ISSUE TITLE
Possibly wrong handling of MIDI data in AudioProcessorGraph::AudioGraphIOProcessor

### ISSUE THREAD

**Issue by hkarim** [WeAreROLI/JUCE#144]
Method `AudioProcessorGraph::AudioGraphIOProcessor::processAudio` is possibly not handling the MIDI buffer copying correctly:

```c
graph->currentMidiOutputBuffer.addEvents (midiMessages, 0, buffer.getNumSamples(), 0);
```

since `buffer.getNumSamples()` is not relevant here.

See [here](https://github.com/julianstorer/JUCE/blob/master/modules/juce_audio_processors/processors/juce_AudioProcessorGraph.cpp#L1603) and [here](https://github.com/julianstorer/JUCE/blob/master/modules/juce_audio_processors/processors/juce_AudioProcessorGraph.cpp#L1607)

Also, maybe swapping the buffer would be more appropriate in this context, instead of the looping, right?

**Comment by julianstorer** [comment]
Sorry, can't really see a problem with that code.. If you want to discuss how it works in more detail, the forum would be a better place than in bug reports like this.
