### ISSUE TITLE
Number of input / output channels is incorrect in prepareToPlay() for certain VST3 plugins

### ISSUE THREAD

**Issue by devinkerr** [WeAreROLI/JUCE#148]
If the constructor in GainPlugIn is changed to just `AudioProcessor()`, and `isBusesLayoutSupported` is altered to support a channel config of {2, 2}, then `prepareToPlay` is called with {0, 0} input / output channels (instead of the expected {2, 2}).

Notes: 
- `processBlock` is correctly called with {2, 2} channels. 
- `prepareToPlay` is called before any calls to `isBusesLayoutSupported` are observed. Is this expected?
- Tested in REAPER, Mac OS X 10.11, JUCE 4.3.0

**Comment by tpoole** [comment]
See the JUCE forum thread: https://forum.juce.com/t/number-of-input-output-channels-is-incorrect-in-preparetoplay-for-certain-vst3-plugins/20635
