### ISSUE TITLE
D82 Sonic Maximizer  Crashes Juce Plugin Host

### ISSUE THREAD

**Issue by MrYZD** [WeAreROLI/JUCE#162]
On latest tip, compiled the plugin host demo
Running Windows 7 x64
64 bit version of host.
VST version of plugin (Only available)

## I Use the host load vst plugin（D82 Sonic Maximizer）

An error code in this file ( juce_VSTPluginFormat.cpp )

  void closeEffect (VstEffectInterface* eff)
    {
        eff->dispatchFunction (eff, plugInOpcodeClose, 0, 0, 0, 0);
    }

## I usr vs 2015  to debug the error below:

 	ntdll.dll!_RtlReportCriticalFailure@8()	未知
 	ntdll.dll!_RtlpReportHeapFailure@4()	未知
 	ntdll.dll!_RtlpLogHeapFailure@24()	未知
 	ntdll.dll!_RtlFreeHeap@12()	未知
 	kernel32.dll!_HeapFree@12()	未知
 	D82 Sonic Maximizer .dll!0d482d3a()	未知
 	[下面的框架可能不正确和/或缺失，没有为 D82 Sonic Maximizer .dll 加载符号]	
 	D82 Sonic Maximizer .dll!0d471223()	未知
 	D82 Sonic Maximizer .dll!0d472a78()	未知
 	D82 Sonic Maximizer .dll!0d476ded()	未知
>	Plugin Host.exe!juce::ModuleHandle::closeEffect(juce::`anonymous-namespace'::VstEffectInterface * eff) 行 444	C++
 	Plugin Host.exe!juce::VSTPluginInstance::cleanup() 行 658	C++
 	Plugin Host.exe!`juce::VSTPluginInstance::~VSTPluginInstance'::`5'::VSTDeleter::messageCallback() 行 620	C++
 	Plugin Host.exe!juce::WindowsMessageHelpers::dispatchMessageFromLParam(long lParam) 行 49	C++
 	Plugin Host.exe!juce::MessageManager::dispatchNextMessageOnSystemQueue(bool returnIfNoPendingMessages) 行 122	C++
 	Plugin Host.exe!juce::MessageManager::runDispatchLoop() 行 130	C++
 	Plugin Host.exe!juce::JUCEApplicationBase::main() 行 244	C++
 	Plugin Host.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) 行 136	C++
 	[外部代码]	

What causes this problem ？？？ How to fix. ths.

**Comment by hogliux** [comment]
Very hard to say what the problem is without access to the source code of the plug-in. You might need to report this to BBE. We are happy to help debug this but we would likely need their assistance.

**Comment by MrYZD** [comment]
According to this article ：
https://forum.juce.com/t/vst-loading-crash-modulehandle-closeeffect/11195

Should be the  juce  read plug-in version of the problem.


I have already sent an E-mail to you, mail there are related plug-ins.
Trouble help debug plugin to find problems, thank you

**Comment by hogliux** [comment]
The forum link that you cited is more than 5 years old. I don't think it is relevant anymore.

Also, the .dll binary you sent me is crashing all my hosts - including Ableton Live, Cubase and Bitwig. I don't think this is a JUCE bug.
