### ISSUE TITLE
MenuBar disappears, reappears when resizing Projucer - develop branch, windows, vs2015 64bit

### ISSUE THREAD

**Issue by sofakid** [WeAreROLI/JUCE#166]
Environment details: 
This is on Windows 10 pro, building with VS2015, 64 bit Release and Debug. I have not tried 32 bit.

To Reproduce: 
Build latest Projucer on develop branch. Run it and open a project. Resize the window. As you resize, the main menu bar will disappear, and the tree view and code editor will shift up, leaving blank space at the bottom of the window. If you stop resizing while it's gone, it will stay like that, if you resize more, the menu bar will reappear. Maximizing the window also makes it disappear.

**Comment by julianstorer** [comment]
the projucer's GUI has been totally refactored in JUCE 5 so am presuming that this bug is no longer relevant - please re-open if this still happens in JUCE 5.

**Comment by sofakid** [comment]
Looks all good now. Thank you.
