### ISSUE TITLE
JUCE 4.3.1 breaks compilation in VS2012

### ISSUE THREAD

**Issue by tico-tico** [WeAreROLI/JUCE#172]
juce_CompilerSupport.h

```c++
 #if _MSC_VER >= 1700
  #define JUCE_COMPILER_SUPPORTS_OVERRIDE_AND_FINAL 1
  #define JUCE_COMPILER_SUPPORTS_LAMBDAS 1
 #endif
```
 
juce_Variant.h
```c++
   #if JUCE_COMPILER_SUPPORTS_LAMBDAS
    using NativeFunction = std::function<var (const NativeFunctionArgs&)>;
   #else
    typedef var (*NativeFunction) (const NativeFunctionArgs&);
   #end
```
   
`Error	1	error C2873: 'NativeFunction' : symbol cannot be used in a using-declaration (..\..\JuceLibraryCode\juce_audio_basics.cpp)	d:\sources\[dexed]\jucelibrarycode\modules\juce_core\containers\juce_Variant.h	67	1	Dexed`

I doubt that VS2012 supports such using of **using**.

**Comment by tpoole** [comment]
VS2012 is no longer supported on the develop branch, and support will be dropped on the master branch after the launch of JUCE 5 in a few weeks. The solution is to upgrade to a more modern version of Visual Studio.
