### ISSUE TITLE
Projucer config tab automatic focus on root node

### ISSUE THREAD

**Issue by memetea** [WeAreROLI/JUCE#173]
1) projucer.exe will automatically set focus to the root node of the tree component in the Config tab
  2) the focus should be stay on my selected item
  3) windows 7
  4) 64-bit
  5) none
  6) none
  7) none

**Comment by komorra** [comment]
Temporary workaround that works for me is to turn on from main menu Build->Enable Compilation. After that focus stays as it should, and also input fields doesn't lost focus.

**Comment by AxelStrem** [comment]
I have the same issue under windows 7 64-bit, extremely annoying. Does not appear in Linux though.

**Comment by julianstorer** [comment]
Given that the treeviews have all been completely rewritten in the latest projucer, I'm assuming this is no longer an issue, but please reopen or post a new bug if it is.
