### ISSUE TITLE
MessageManager loop not serviced when displaying native FileChooser dialog in linux

### ISSUE THREAD

**Issue by jearnshaw** [WeAreROLI/JUCE#177]
It would be nice if the native FileChooser dialog did not block the message thread while waiting for the child process to exit. This halts numerous things in the system which you would expect to remain running in the background with a dialog box active, eg: Timers & OpenGLRenderer. The following code shows an example of a possible fix:

juce_linux_FileChooser.cpp::FileChooser::showPlatformDialog() 

```
    ...
    if (child.start (args, ChildProcess::wantStdOut))
    {
        if (MessageManager::getInstance()->isThisTheMessageThread())
        {
            while (child.isRunning())
            {
                if (!MessageManager::getInstance()->runDispatchLoopUntil(20))
                    break;
            }
        }
        
        const String result (child.readAllProcessOutput().trim());

        if (result.isNotEmpty())
        {
        ...
```

**Comment by hogliux** [comment]
Fixed with commit 	[d6b1796](https://github.com/WeAreROLI/JUCE/commit/d6b1796361db8bb004d9e3cb497c1c21d97be669).
