### ISSUE TITLE
Projucer: Old LookAndFeel is used when previewing a GUI Component via cmd+t

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#184]
I'm on Mac OS and got the Projucer from the website. If you create a new GUI component and a few buttons, the JUCE5 LookAndFeel is used in the GUI Editor. If you press cmd+t to preview the component, the window opens, but the old LookAndFeel is used.

**Comment by ed95** [comment]
Fixed in [this commit](https://github.com/WeAreROLI/JUCE/commit/b9f5b6e4b18fea23f4dd3e43014cb8a141728fa0)
