### ISSUE TITLE
[class] ColourSelector, undersired constness of a virtual method setter

### ISSUE THREAD

**Issue by dowail** [WeAreROLI/JUCE#186]
`virtual void setSwatchColour (int index, const Colour& newColour) const;`
should not be **const**
[source](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_gui_extra/misc/juce_ColourSelector.h#L113)

**Comment by julianstorer** [comment]
Thanks, didn't know about that, will sort it out!
