### ISSUE TITLE
Link error with webkit disabled in juce_gui_extra (From forum)

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#189]
If you set the macro JUCE_WEB_BROWSER=0 to avoid webkit, then the application fails to link with:

In function `juce::JUCEApplicationBase::main(int, char const**, void*)':
include_juce_events.cpp:(.text.startup+0x1ae): undefined reference to `juce::juce_gtkWebkitMain(int, char const**)'

On the forum, there is a proposal to add :
&& JUCE_WEB_BROWSER to the #if just prior to that line in JUCEApplicationBase::main() (line 217)

**Comment by julianstorer** [comment]
This has been fixed
