### ISSUE TITLE
undeclared identifier 'WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER' on linux (yakkety)

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#190]
When building with linux, getting this error on travis :

In file included from ../../../JUCE/modules/juce_gui_extra/juce_gui_extra.cpp:140:
../../../JUCE/modules/juce_gui_extra/native/juce_linux_X11_WebBrowserComponent.cpp:166:69: error: 
      use of undeclared identifier 'WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER'
        webkit_settings_set_hardware_acceleration_policy (settings, WEBK...

I was not able to find anywhere which version of webkit2gtk i must install

**Comment by rghvdberg** [comment]
I'm on zesty and had to install libwebkit2gtk-4.0-dev

**Comment by hogliux** [comment]
This is fixed with JUCE 5.0.1 (see commit #a1794b1143fc0cde774ad4a6b0e324d58c12173d)
