### ISSUE TITLE
Projucer is taking 100% of CPU (Windows 10)

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#192]
When launching projucer,
it automatically raise up to 100% of CPU usage.

Tried to recompile a release version of the one included, same result.
![projucer100](https://cloud.githubusercontent.com/assets/1291595/25564479/58631974-2db4-11e7-815c-50d0c81e9db9.jpg)

**Comment by julianstorer** [comment]
Not something we can reproduce...

Obviously when the live compiler is running, it can use a lot of CPU, but if it's doing this when idle you'd need to profile it to see where it's all going so we could take a look.
