### ISSUE TITLE
MidiMessage::endOfTrack()  at VS2015

### ISSUE THREAD

**Issue by kawaCat** [WeAreROLI/JUCE#195]
Hi. Thank you JUCE5 .
( sorry my english skill is not fine.  )

I found unexpected result in "MidiMessage::endOfTrack()" at VS2015, and I fix it.
( at before fixed , created midi file could not reading at Reaper and Studio One. )

**file**  : juce_audio_basics/midi/juce_MidiMessage.cpp 
**line** : 858

```
MidiMessage MidiMessage::endOfTrack() noexcept
{
    return { 0xff, 0x2f };
}
```

to 

```
MidiMessage MidiMessage::endOfTrack() noexcept
{
    return { 0xff, 0x2f, 0 };  // added third argument.
}
```

Best regards,
thank you !

**Comment by julianstorer** [comment]
Thanks very much! I've sorted that out now.
