### ISSUE TITLE
DownloadClickDetectorClass::didFailLoadWithError() always crashes 

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#196]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

- Download JUCE 5
- Compile and run the JUCE Demo example
- Open the Web Browser demo
- Type some garbage in the address bar and click "Go"

Expected behaviour:

- My ISP's "Page not found" is displayed

Actual behaviour:

- JUCE fails an assertion in String::String(const char* const t)

  3) the operating system

OS X 10.12

  4) the architecture (32-bit or 64-bit)

64-bit

  5) a stack trace - if the bug causes a crash

#0	0x00000001002ec89f in juce::String::String(char const*) at ../../../../modules/juce_core/text/juce_String.cpp:321
#1	0x00000001002c093d in juce::String::String(char const*) at ../../../../modules/juce_core/text/juce_String.cpp:303
#2	0x00000001006b2f84 in juce::DownloadClickDetectorClass::didFailLoadWithError(objc_object*, objc_selector*, WebView*, NSError*, WebFrame*) at ../../../../modules/juce_gui_extra/native/juce_mac_WebBrowserComponent.mm:91

--

The problem is occurring in `DownloadClickDetectorClass::didFailLoadWithError()` because `errorString` is a UTF8 string and therefore needs wrapping with `CharPointer_UTF8()`

**Comment by julianstorer** [comment]
What you're saying doesn't seem to match the latest code.. I'm guessing this has already been fixed.

**Comment by jamiebullock** [comment]
OK, looks like it's been fixed in 6475111
