### ISSUE TITLE
Incorrect system stats in Juce Demo on Windows 10

### ISSUE THREAD

**Issue by KoenTanghe** [WeAreROLI/JUCE#199]
Steps to reproduce:

1. Switch to Develop branch + pull to get latest updates (today is 2017-05-04, hash = dc2ec6fc9df135a4c8f3368674e9676096a7db61)
2. Build ProJucer, open Juce Demo project in ProJucer, save project
3. Build + run Juce Demo (in Release mode, 64-bit)
4. Go to the "System info" demo
5. On my system (Windows 10, all the latest updates, 64-bit) I see the following things:

"System up-time:   1 week 5 days"
I just started my computer this morning (about 2 hours ago), from a full shutdown last night. So this can't be correct.

"Operating system: Windows 8.0"
This is Windows 10 with all the latest updates, so that doesn't seem correct either.

Just reporting this, not a real issue for me personally at the moment though.

**Comment by otristan** [comment]
https://forum.juce.com/t/bug-systemstats-getoperatingsystemname-on-windows-10/21659

**Comment by reFX-Mike** [comment]
There is simple way to do it. Get the version information from kernel32.dll

If there is interest in that approach, I can post the code here. It's very simple.

**Comment by jrlanglois** [comment]
Can't this issue be closed now?

**Comment by reFX-Mike** [comment]
The fix in develop looks fine.
