### ISSUE TITLE
FileChooser native dialog fails to display when given path with drive letter that does not exist

### ISSUE THREAD

**Issue by yfede** [WeAreROLI/JUCE#200]
This is a Windows specific issue.
Tested with JUCE 4.3 and 5.0.0 (although I believe it has not been fixed in 5.0.1) in 64-bit build

Minimal code to reproduce:
(replace "L:" with the letter of a drive that does **not** exist on the computer where you test this)

        FileChooser chooser ("Choose audio files to import", File ("L:"), "*.wav", true);
        const bool result = chooser.browseForMultipleFilesToOpen();

Expected behavior: 

the file chooser dialog should appear, pointing to a default folder because the path given does not exist. I believe this is already the behavior if one specifies a path that does not exist but it is on an existing drive (e.g. "C:")

Actual behavior:

the second line never displays a file chooser dialog. Instead, it always silently fails returning `false` in `result`

**Comment by tpoole** [comment]
Fixed in 9b065f12b4de5ed4ef32d28cd4b2e1958590f017
