### ISSUE TITLE
[LINUX] Projucer - blank windows

### ISSUE THREAD

**Issue by rghvdberg** [WeAreROLI/JUCE#201]
Linux Kubuntu 17.04
I compiled Projucer from git without errors

When I run Projecer I get a blank window although on only one occasion I got into the login screen.

**Comment by hogliux** [comment]
I'm currently looking into this issue. It seems that there is a race condition when the WebBrowserComponent is resized: it will sometimes remain in it's initial 10x10 pixel size.

**Comment by hogliux** [comment]
Fixed with commit 	[d6d6992](https://github.com/WeAreROLI/JUCE/commit/d6d699214adb1e8a79e1e54107447c0db8de9893). Linux binaries will be re-built with this fix.
