### ISSUE TITLE
Additional overload for DBG

### ISSUE THREAD

**Issue by leehu** [WeAreROLI/JUCE#203]
This is valid on Mac:

    bool flag = true;
    DBG( "flag: " << flag );

but on Windows I have to cast it:
    bool flag = true;
    DBG( "flag: " << (int)flag );

Any chance this could be addressed on Windows so I don't have to cast all bools. thx

**Comment by yfede** [comment]
I don't think this has to do with overloads of DBG
You should get the same problem if you do the same << operation outside of a DBG, right?
Maybe an overload of String::operator<<(bool) that's needed instead

**Comment by tpoole** [comment]
Added: https://github.com/WeAreROLI/JUCE/commit/041feb16883bd0ff7c76a6de5c8b21209a7f7d95

**Comment by tpoole** [comment]
Having thought about this a bit more, a much better approach is to prevent the above behaviour on MacOS and force JUCE users to cast all bools to ints. This avoids a lot of nasty type conversion edge cases.

https://github.com/WeAreROLI/JUCE/commit/d59ac51067e59b906d466200a41bfc7f8cbedf02

https://forum.juce.com/t/breaking-change-minor-string-bool-constructor-explicitly-deleted/23859
