### ISSUE TITLE
Memory leaks detected after playing with plugin host example in latest 5.0.2

### ISSUE THREAD

**Issue by fab672000** [WeAreROLI/JUCE#211]
1) Built plugin host example for osx 10.12.5 , 64-bit from the master 5.0.2 released version,
then started debugging.
  2) While closing app in debug mode, started from the xcode debugger: juce_LeakedObjectDetector class helper indicates that PopupMenu object leaks:

*** Leaked objects detected: 8 instance(s) of class PopupMenu
JUCE Assertion failure in juce_LeakedObjectDetector.h:88

was using VST format synthesizers all plugged to main output L/R channels

Also, stack was:
(lldb) bt
* thread #1, name = 'Juce Message Thread', queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
  * frame #0: 0x0000000100537dd7 Plugin Host`juce::LeakedObjectDetector<juce::PopupMenu>::LeakCounter::~LeakCounter(this=0x000000010068cc98) at juce_LeakedObjectDetector.h:88
    frame #1: 0x0000000100537cc5 Plugin Host`juce::LeakedObjectDetector<juce::PopupMenu>::LeakCounter::~LeakCounter(this=0x000000010068cc98) at juce_LeakedObjectDetector.h:76
    frame #2: 0x00007fff95209178 libsystem_c.dylib`__cxa_finalize_ranges + 332
    frame #3: 0x00007fff952094b2 libsystem_c.dylib`exit + 55
    frame #4: 0x00007fff7d140882 AppKit`-[NSApplication terminate:] + 1851
    frame #5: 0x00007fff953a63a7 libsystem_trace.dylib`_os_activity_initiate_impl + 53
    frame #6: 0x00007fff7d6bd721 AppKit`-[NSApplication(NSResponder) sendAction:to:from:] + 456
    frame #7: 0x00007fff7d190666 AppKit`-[NSMenuItem _corePerformAction] + 324
    frame #8: 0x00007fff7d1903d2 AppKit`-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
    frame #9: 0x00007fff953a63a7 libsystem_trace.dylib`_os_activity_initiate_impl + 53
    frame #10: 0x00007fff7d219955 AppKit`-[NSMenu performActionForItemAtIndex:] + 121
    frame #11: 0x00007fff7d2198cc AppKit`-[NSMenu _internalPerformActionForItemAtIndex:] + 94
    frame #12: 0x00007fff7d2196f9 AppKit`-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
    frame #13: 0x00007fff7d0d0580 AppKit`NSSLMMenuEventHandler + 986
    frame #14: 0x00007fff7e97ed85 HIToolbox`DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1708
    frame #15: 0x00007fff7e97dff6 HIToolbox`SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 428
    frame #16: 0x00007fff7e993d14 HIToolbox`SendEventToEventTarget + 40
    frame #17: 0x00007fff7e9e03e6 HIToolbox`SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 411
    frame #18: 0x00007fff7ea0b9fb HIToolbox`SendMenuCommandWithContextAndModifiers + 59
    frame #19: 0x00007fff7ea0b9aa HIToolbox`SendMenuItemSelectedEvent + 188
    frame #20: 0x00007fff7ea0b87d HIToolbox`FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
    frame #21: 0x00007fff7ea0c2b7 HIToolbox`MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 702
    frame #22: 0x00007fff7ea0bf66 HIToolbox`_HandleMenuSelection2 + 460
    frame #23: 0x00007fff7d0c0368 AppKit`_NSHandleCarbonMenuEvent + 239
    frame #24: 0x00007fff7d33a702 AppKit`_DPSEventHandledByCarbon + 54
    frame #25: 0x00007fff7d6bb0c5 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 963
    frame #26: 0x00000001002ace68 Plugin Host`juce::MessageManager::runDispatchLoopUntil(this=0x00006180000c0540, millisecondsToRunFor=20) at juce_mac_MessageManager.mm:298
    frame #27: 0x00000001003bd083 Plugin Host`juce::ModalComponentManager::runEventLoopForCurrentComponent(this=0x000061000006ffc0) at juce_ModalComponentManager.cpp:288
    frame #28: 0x00000001003bcd04 Plugin Host`juce::Component::runModalLoop(this=0x0000000102018d30) at juce_Component.cpp:1718
    frame #29: 0x0000000100457dd8 Plugin Host`juce::PopupMenu::showWithOptionalCallback(this=0x00007fff5fbfe578, options=0x00007fff5fbfe4e0, userCallback=0x0000000000000000, canBeModal=true) at juce_PopupMenu.cpp:1623
    frame #30: 0x000000010045803d Plugin Host`juce::PopupMenu::show(this=0x00007fff5fbfe578, itemIDThatMustBeVisible=0, minimumWidth=0, maximumNumColumns=0, standardItemHeight=0, callback=0x0000000000000000) at juce_PopupMenu.cpp:1657
    frame #31: 0x000000010000ea79 Plugin Host`GraphEditorPanel::mouseDown(this=0x00006000001c1680, e=0x00007fff5fbfe720) at GraphEditorPanel.cpp:855
    frame #32: 0x00000001003c2856 Plugin Host`juce::Component::internalMouseDown(this=0x00006000001c1680, source=MouseInputSource @ 0x00007fff5fbfe8f0, relativePos=(x = 787.28125, y = 197.429688), time=(millisSinceEpoch = 1496972967406), pressure=1, orientation=0, rotation=0, tiltX=0, tiltY=0) at juce_Component.cpp:2480
    frame #33: 0x00000001004b2f55 Plugin Host`juce::MouseInputSourceInternal::sendMouseDown(this=0x00006180001a01c0, comp=0x00006000001c1680, screenPos=(x = 1506.28125, y = 513.429688), time=(millisSinceEpoch = 1496972967406)) at juce_MouseInputSource.cpp:142
    frame #34: 0x00000001004b19f2 Plugin Host`juce::MouseInputSourceInternal::setButtons(this=0x00006180001a01c0, screenPos=(x = 1506.28125, y = 513.429688), time=(millisSinceEpoch = 1496972967406), newButtonState=(flags = 32)) at juce_MouseInputSource.cpp:214
    frame #35: 0x00000001003c7302 Plugin Host`juce::MouseInputSourceInternal::handleEvent(this=0x00006180001a01c0, newPeer=0x0000600000161200, positionWithinPeer=(x = 787.28125, y = 197.429688), time=(millisSinceEpoch = 1496972967406), newMods=(flags = 32), newPressure=1, newOrientation=0, pen=(rotation = 0, tiltX = 0, tiltY = 0)) at juce_MouseInputSource.cpp:331
    frame #36: 0x00000001003c6f2b Plugin Host`juce::MouseInputSource::handleEvent(this=0x00007fff5fbfed30, peer=0x0000600000161200, pos=<unavailable>, time=1496972967406, mods=(flags = 32), pressure=1, orientation=0, pen=0x00007fff5fbfed80) at juce_MouseInputSource.cpp:616
    frame #37: 0x0000000100496c80 Plugin Host`juce::ComponentPeer::handleMouseEvent(this=0x0000600000161200, type=mouse, pos=(x = 787.28125, y = 197.429688), newMods=(flags = 32), newPressure=1, newOrientation=0, time=1496972967406, pen=(rotation = 0, tiltX = 0, tiltY = 0), touchIndex=0) at juce_ComponentPeer.cpp:85
    frame #38: 0x0000000100505061 Plugin Host`juce::NSViewComponentPeer::sendMouseEvent(this=0x0000600000161200, ev=0x00006180001250a0) at juce_mac_NSViewComponentPeer.mm:681
    frame #39: 0x0000000100504f28 Plugin Host`juce::NSViewComponentPeer::redirectMouseDown(this=0x0000600000161200, ev=0x00006180001250a0) at juce_mac_NSViewComponentPeer.mm:545
    frame #40: 0x0000000100502349 Plugin Host`juce::JuceNSViewClass::asyncMouseDown(self=0x0000600000120be0, (null)="rightMouseDown:", ev=0x00006180001250a0) at juce_mac_NSViewComponentPeer.mm:1599
    frame #41: 0x00000001005022d7 Plugin Host`juce::JuceNSViewClass::mouseDown(self=0x0000600000120be0, s="rightMouseDown:", ev=0x00006180001250a0) at juce_mac_NSViewComponentPeer.mm:1576
    frame #42: 0x00007fff7d836c10 AppKit`-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6458
    frame #43: 0x00007fff7d834f0a AppKit`-[NSWindow(NSEventRouting) sendEvent:] + 541
    frame #44: 0x00007fff7d6b9e7e AppKit`-[NSApplication(NSEvent) sendEvent:] + 3190
    frame #45: 0x00007fff7cf34427 AppKit`-[NSApplication run] + 1002
    frame #46: 0x00000001002a5b83 Plugin Host`juce::MessageManager::runDispatchLoop(this=0x00006180000c0540) at juce_mac_MessageManager.mm:247
    frame #47: 0x00000001002a5a75 Plugin Host`juce::JUCEApplicationBase::main() at juce_ApplicationBase.cpp:260
    frame #48: 0x00000001002a588c Plugin Host`juce::JUCEApplicationBase::main(argc=3, argv=0x00007fff5fbff6e0) at juce_ApplicationBase.cpp:238
    frame #49: 0x0000000100018533 Plugin Host`main(argc=3, argv=0x00007fff5fbff6e0) at HostStartup.cpp:133
    frame #50: 0x00007fff95174235 libdyld.dylib`start + 1

**Comment by ed95** [comment]
This has been fixed in the current version of JUCE.
