### ISSUE TITLE
JUCE Modules: Features and Documentation 

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#212]
Hi

**Support for fat binaries in iOS in JUCE modules**

The current way JUCE modules refer precompiled static libraries does not take into account that XCode generates fat binaries (basically a single .a file that contains all the desired architectures in it), see [JUCE Module Format.txt](https://github.com/WeAreROLI/JUCE/blob/master/modules/JUCE%20Module%20Format.txt#L123).

Maybe a 'fat' architecture would allow to mirror this mechanism?

For now I'll try to use the linker settings to explicitly reference the library (thus bypassing the folder-name-based JUCE module approach.)

If for any reason you believe supporting fat binaries would create complications, a mention in the JUCE Module Format document would help.

**no androidLibs value definition**

On a side note, [there is no **androidLibs** value definition](https://github.com/WeAreROLI/JUCE/blob/master/modules/JUCE%20Module%20Format.txt#L146), thus the only way to reference a static library in an Android module is to use the linker flags via Projucer. 
If there's any reason why this has to stay like this, a mention could go into the JUCE Module Format doc.

Regards

**Comment by tpoole** [comment]
We'll add this to the backlog. A quick solution is to place symlinks to the same library in each supported architecture directory. Clearly this isn't as convenient, but it would save adding linker settings.

I've just added support for static libraries in Android: 4965cdf0305ba7b752b400b84b1dd77c73d1764d
