### ISSUE TITLE
The Projucer adds Windows line endings (^M) to any source file referenced in the File Explorer

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#214]
This breaks the git history and makes git diff (without [extra "workaround" flags](https://coderwall.com/p/crj69a/from-a-useless-git-diff-to-a-useful-one) ) totally useless.

**Comment by mathieu-b** [comment]
Of course it is not a problem with files generated in the Projucer or created from scratch.

However it becomes an issue when files from other separate non-JUCE projects are referenced, for example when creating a static library project.

**Comment by mathieu-b** [comment]
Maybe related to: https://github.com/WeAreROLI/JUCE/blob/f08aa821b6be6a71f774bf7a163258ac0bbe0a22/modules/juce_core/text/juce_NewLine.h#L43
...

**Comment by tpoole** [comment]
Fixed in 1f40a7b10e1dda7ecc4d0d2715a2482224a6d1e1.
