### ISSUE TITLE
Projucer Android Studio Exporter: missing closing quotes on global preprocessor definitions in generated CMakeLists.txt

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#215]
To reproduce this:

1) Create a new Android Application project from the Projucer.

2) Access the "global project settings" (?) by clicking the gear icon near the left-top side of the Projucer UI.

3) In the field "Preprocessor definitions", add the following: 
```
PEDRO
CONCHITA=42
GIGI
GIOVANNI
```

4) Verify that the generated ```app/CmakeLists.txt``` contains the following code: 
```
add_definitions( <_standard_juce_definitions_>  "-DPEDRO "-DCONCHITA=42" "-DGIGI "-DGIOVANNI)
```

Only the definition that had a '=42' after it got properly closed. (also any other number will do, and maybe also any symbol.)

The very bad part is that this causes Android Studio to stall indefinitely in the "Refreshing 'Android' Gradle Project" until the memory runs out and it has to be forcefully closed, basically making it impossible to build and deploy on Android.
This happens on both Windows and OSX.

Another variant of the issue is the following:

1) in the field "Preprocessor definitions", set the following: 
```
PEDRO
CONCHITA=42
GIGI=
GIOVANNI
```

2) Verify that the generated ```app/CmakeLists.txt``` contains the following code: 
```
add_definitions( <_standard_juce_definitions_>   "-DPEDRO "-DCONCHITA=42" "-DGIGI=GIOVANNI")
```

At least this does not get Android Studio stuck forever, probably thanks to the last closing quotes...

**Comment by hogliux** [comment]
This is fixed now on develop. Thanks for reporting!

**Comment by mathieu-b** [comment]
Great :)
Thanks
