### ISSUE TITLE
MidiTest example: Virtual MIDI Output device listed as Input (OSX)

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#223]
This happens in JUCE 5.0.2 release.

To reproduce the issue:

1. Open the **MidiTest** example
2. add the code to create a virtual MIDI Output device:
  * In the `MainComponent.h` header, add a `MidiOutput` member variable:
        
        ScopedPointer<MidiOutput> mVirtualMidiOutput;
        
  * At the beginning of the `MainComponent` constructor in `MainComponent.cpp`, create the output device:
        
        mVirtualMidiOutput = juce::MidiOutput::createNewDevice ("MIDI-OUT");
        
3. Notice that the created `MIDI-OUT` device appears in the list of inputs.

**Comment by tpoole** [comment]
When you create a virtual output device the object you get back is a MIDI output - you can write data to it. There shouldn’t be any confusion here.

Once you have created the device, if you *query the operating system for available devices*, you will see the same virtual MIDI device with data available to be read from it - this is a MIDI input.
