### ISSUE TITLE
Projucer text editor colors change when About Projucer dialog opened

### ISSUE THREAD

**Issue by cpr2323** [WeAreROLI/JUCE#236]
1) Bringing up any of the dialogs from the File menu (About Projucer, Application Usage Data, or Global Search Paths) causes the text editor colors change. But, this doesn’t happen if I first bring up one of the dialogs from the Tools menu, and then open one of the dialogs from the File menu. So, the easiest recipe is launch Projucer and open one of the dialogs from the File menu.
2) Expected behavior is that the text editor colors should not change.
3) Win7
4) 64bit

Correct colors:
![projucer_colors_correct](https://user-images.githubusercontent.com/3159629/29251660-a99d1d2a-800d-11e7-8458-a1d005145929.png)

Incorrect colors:
![projucer_colors_wrong](https://user-images.githubusercontent.com/3159629/29251663-b7e93ba2-800d-11e7-973c-8e407c0d6a40.png)

**Comment by ed95** [comment]
Fixed with commit [6b315c4](https://github.com/WeAreROLI/JUCE/commit/6b315c4e15a18154112abf7583bb7787cc5fef02)
