### ISSUE TITLE
Setting macOS Deployment Target in ProJucer doesn't update Xcode build settings in the "- All" target

### ISSUE THREAD

**Issue by jeroendreessen** [WeAreROLI/JUCE#238]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code
- Create new Audio Plugin projucer project
- Set OSX Deployment Target to e.g. 10.9 in ProJucer
- Save and open in Xcode
- Check macOS Deployment Target in Build Settings under the "- All" target
- It is not 10.9, but the default version (10.12 in my case) 
- The other targets (VST, AU, Shared code, ..) do seem to have the right target version

  2) the expected behaviour
- In all Xcode Build settings the Deployment target is the same as the version set in ProJucer

  3) the operating system
- OSX 10.12.5

  4) the architecture (32-bit or 64-bit)
  5) a stack trace - if the bug causes a crash
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
  7) which DAW you observed the bug in - if applicable

Make sure you have pulled the latest commits from the JUCE repo and re-compiled
the Projucer before you submit your bug. If it's a major bug, which must be
hot-fixed immediately, then we will also accept bug reports for tagged release
versions.

**Comment by ed95** [comment]
The "all" target doesn't have an associated product or build rules, it just builds a group of targets at once (VST, AU, standalone etc.) that all have their own build settings so there's really no point in changing any of it's build settings to anything other than the default.

**Comment by francoisbecker** [comment]
Yet, the "All" target executes pre-build scripts as well as post-build scripts, which would access this property in some configurations.

**Comment by ed95** [comment]
Good point, should be fixed with [1bea9dd](https://github.com/WeAreROLI/JUCE/commit/1bea9dd0f8e3076916fb48028fc5caf0dbf4ac6c)
