### ISSUE TITLE
HashMap fails if key is INT_MIN

### ISSUE THREAD

**Issue by hjmallon** [WeAreROLI/JUCE#240]
`HashMap<int, int> hashMap;
hashMap.set(std::numeric_limits<int>::min(), 0);`

  1) Create HashMap<int, int>. Add something with key = std::numeric_limits<int>::min()
  2) It should let you do this
  3) It asserts here 
`jassert (isPositiveAndBelow (hash, numSlots)); // your hash function is generating out-of-range numbers!`

std::abs(std::numeric_limits<int>::min()) == std::numeric_limits<int>::min() (on Clang and GCC, it is undefined in general) so the hash is negative.

Suggested solution would be a function matching the void* one:
int generateHash (const int key, const int upperLimit) const noexcept        { return (int) (((uint32) key) % (uint32) upperLimit); }

The same applies to the int64 version.

**Comment by reFX-Mike** [comment]
I recommend not using the HashMap at all in this case. Use a std::unordered_map and you'll be much happier.

**Comment by hjmallon** [comment]
@reFX-Mike unordered_map is great. We use it in most of our new code. This was just a bugfix we made for our legacy code (I am currently in the process of synchronising our JUCE codebase with upstream).

**Comment by julianstorer** [comment]
Thanks - I'll get a fix for that pushed today.
