### ISSUE TITLE
Can't do Select All on read only TextEditor

### ISSUE THREAD

**Issue by hjmallon** [WeAreROLI/JUCE#241]
In a TextEditor that is isReadOnly() you can't select all to copy the contents (you can do copy). I propose a code change as follows to enable select all as well:

```
bool TextEditor::keyPressed (const KeyPress& key)
{
    if (isReadOnly() && key != KeyPress ('c', ModifierKeys::commandModifier, 0)
                               && key != KeyPress ('a', ModifierKeys::commandModifier, 0))
        return false;
...
```

**Comment by ed95** [comment]
Thanks, added here - [12e99c7](https://github.com/WeAreROLI/JUCE/commit/12e99c715204fb7f3d6957ca258fd941dde1e3dd)
