### ISSUE TITLE
Process::raisePrivilege() and Process::lowerPrivilege() assert inconsistently

### ISSUE THREAD

**Issue by hjmallon** [WeAreROLI/JUCE#242]
Process::raisePrivilege() and Process::lowerPrivilege() are only supported on Linux. My issue is that the behaviour on platforms where it is not supported is inconsistent:

Android: Empty function
Mac/Win32: Assert

Could we remove the asserts on Mac and Windows? The comment on the function already says "Does nothing if this isn't supported by the current OS, or if process privilege level is fixed." so that would be consistent (an assert is only kind-of nothing).

**Comment by ed95** [comment]
Added in [4baf519](https://github.com/WeAreROLI/JUCE/commit/4baf5197006bce94e64926d687aebff7f35c2798) - thanks for reporting!
