### ISSUE TITLE
ChildProcess::waitForProcessToFinish erases exit code (Linux)

### ISSUE THREAD

**Issue by singpolyma** [WeAreROLI/JUCE#243]
`waitForProcessToFinish` currently is implemented as a busywait loop over the `isRunning` call -- unfortunately, this means that once `isRunning` has returned true, the `waitpid` call it uses to determine if the process is done has already reaped the child process and now `getExitCode` will always return `0` -- not very useful.

I suggest that on posix platforms `waitForProcessToFinish` should use `waitpid` to do a blocking wait instead of a busy wait, and then return the exit code from itself.

**Comment by ed95** [comment]
I believe this has been fixed in [3064d24](https://github.com/WeAreROLI/JUCE/commit/3064d243b0b3214ae13b285ff2224c74e4941c31).
