### ISSUE TITLE
dsp::Matrix is broken

### ISSUE THREAD

**Issue by m-hilgendorf** [WeAreROLI/JUCE#244]
Attempting to instantiate dsp::Matrix of any type will break. This can be fixed either by moving `    #include "maths/juce_Matrix.cpp"` to juce_dsp.h (right now it's in juce_dsp.cpp) or by adding explicit template instantiation at the bottom of juce_Matrix.cpp. In doing so you'll get another compiler error, which this will fix:

 https://github.com/m-hilgendorf/JUCE/commit/53b2247753c7260609bb21a4dfb63ffa83d82c66

**Comment by tpoole** [comment]
Fixed on the develop branch

https://github.com/WeAreROLI/JUCE/commit/945b3e8a142cf507b3a8e23894d22b441d921042

and cherry picked onto the master branch

https://github.com/WeAreROLI/JUCE/commit/90bbda1f195b4cf940f54f7f41986e0d5d68c9ec

**Comment by m-hilgendorf** [comment]
Thanks for the quick merge. 

Just wanted to add this fix is really quick and dirty. Some additional suggestions that would be great to place in the back log would be to get rid of the toString method, or to make it static and only accept arithmetic types. There's a bunch of places in the cpp file where implicit casts need to be changed for static_cast<>, and it would also be great to be able to create a matrix of Polynomial types. But I get if that's outside the scope of the module, at the moment it's rather SISO/audio focused.
