### ISSUE TITLE
PopupMenu bug caused by border size being zero

### ISSUE THREAD

**Issue by PoliticallyComputer** [WeAreROLI/JUCE#251]
A bug began to appear after [this](https://github.com/WeAreROLI/JUCE/commit/b7a7563a593bb3af90d6e184dc6ebb5dfba5db48) feature was added.

Setting the border size to 0 causes popup menus to be instantly closed upon opening in a certain case: when the popup menu is opened onMouseDown and is shown at the mouse position (the default).

When you press the mouse button down, it opens the popup menu. If the border size is 0, then when the popup menu opens, the mouse’s starting position is over the first item. And then when the right mouse button gets released, it interprets that as a click and selects the first item.

If the border size is 1 or more, the mouse’s starting position is on the border, so the popup menu remains open. I'm using Windows by the way.

I dealt with this problem by opening my popup menu onMouseUp instead of onMouseDown, but apparently on Mac popup menus for right-clicks appear on mouse down.

[Relevant forum post.](https://forum.juce.com/t/popupmenu-bug-caused-by-border-size-being-zero/23800/3)

**Comment by ed95** [comment]
Thanks, this is fixed [here](https://github.com/WeAreROLI/JUCE/commit/8b81379c460f19d1608b6ca92d96d3d615b1231e).
