### ISSUE TITLE
Compile error in juce_Atomic.h

### ISSUE THREAD

**Issue by holzon** [WeAreROLI/JUCE#262]
Don't know what I did to trigger this, but after upgrading to JUCE 5.1.2, XCode started halting with semantic error in JUCE/modules/juce_core/memory/juce_Atomic.h, ln: 57

       #if __cpp_lib_atomic_is_always_lock_free
         static_assert (std::atomic<Type>::is_always_lock_free(),
                        "This class can only be used for lock-free types");
        #endif

is_always_lock_free seems to be a static constexpr variable, not a function, 

http://en.cppreference.com/w/cpp/atomic/atomic/is_always_lock_free

...so the below fix seems to solve the problem for me:

       #if __cpp_lib_atomic_is_always_lock_free
         static_assert (std::atomic<Type>::is_always_lock_free,
                        "This class can only be used for lock-free types");
        #endif

Cheers,
Jens

**Comment by julianstorer** [comment]
Thanks, but we already fixed this a few days ago. Always check the develop branch if you see a problem as we're often already on the case!

**Comment by holzon** [comment]
Gotcha, didn't cross my mind to check!
