### ISSUE TITLE
Expose OSC utility classes: OSCInputStream / OSCOutputStream

### ISSUE THREAD

**Issue by h3xl3r** [WeAreROLI/JUCE#263]
I would like to use JUCE's OSC implementation, but I use my own networking framework, so I am not interested in the OSCSender/OSCReceiver interfaces but purely in the OSC message encoder and decoder classes. Currently these are only visible internally in the implementation files for OSCReceiver and OSCSender. 

It is trivial to expose these as public interfaces to be used independently. AFAIK these were not part of the public interface until now, so this would not be a breaking change, and I can't see any harm done by exposing existing functionality that is already there but hidden away.

Of course I am currently using these classes by maintaining a patch on my own branch, but I can't see a reason this simple change could not be adopted into the master. If required I can send a PR.

**Comment by CharlesHolbrow** [comment]
I would also really like direct access to OSC encoding and decoding.
