### ISSUE TITLE
juce_Atomic doesn't compile with c++1z standard

### ISSUE THREAD

**Issue by danra** [WeAreROLI/JUCE#265]
Due to
         static_assert (std::atomic<Type>::is_always_lock_free(),
                        "This class can only be used for lock-free types");

Should be
         static_assert (std::atomic<Type>::is_always_lock_free,
                        "This class can only be used for lock-free types");

Without the parentheses.
Tested in Xcode 9, but probably also won't compile in any other platform.

**Comment by julianstorer** [comment]
Thanks, but this was fixed on the develop branch last week!
