### ISSUE TITLE
Fatal error compiling Projucer project with Code::Blocks (Linux)

### ISSUE THREAD

**Issue by 0joshuaolson1** [WeAreROLI/JUCE#279]
I'm on an Ubuntu-based OS. Using Projucer, I made an Audio Application, selecting Code::Blocks as the Target Platform. 

When I tried to use Code::Blocks to compile the cbp file in Builds, I get:

```
-------------- Build: App | Debug in NewProject (compiler: GNU GCC Compiler)---------------

g++ -Wall -Wno-strict-aliasing -Wno-strict-overflow -m64 -O0 -std=c++11 -mstackrealign -g -DLINUX=1 -DDEBUG=1 -D_DEBUG=1 -DJUCER_CODEBLOCKS_LINUX_191E0897=1 -DJUCE_APP_VERSION=1.0.0 -DJUCE_APP_VERSION_HEX=0x10000 -DJucePlugin_Build_VST=0 -DJucePlugin_Build_VST3=0 -DJucePlugin_Build_AU=0 -DJucePlugin_Build_AUv3=0 -DJucePlugin_Build_RTAS=0 -DJucePlugin_Build_AAX=0 -DJucePlugin_Build_Standalone=0 -pthread -I. -I../../JuceLibraryCode -I~/JUCE/modules -I/usr/include/freetype2 -c /home/xenox/NewProject/JuceLibraryCode/include_juce_audio_basics.cpp -o obj/Debug/NewProject/JuceLibraryCode/include_juce_audio_basics.o
/home/xenox/NewProject/JuceLibraryCode/include_juce_audio_basics.cpp:9:51: fatal error: juce_audio_basics/juce_audio_basics.cpp: No such file or director
 #include <juce_audio_basics/juce_audio_basics.cpp>
                                                   ^
compilation terminated.
Process terminated with status 1 (0 minute(s), 5 second(s))
1 error(s), 0 warning(s) (0 minute(s), 5 second(s))
```

**Comment by tpoole** [comment]
I'm fairly confident this is just because the path to your modules directory is incorrect. Please check the module settings in the Projucer.

**Comment by 0joshuaolson1** [comment]
I tried again with the same problem, confirming that I gave Projucer the correct path to \<JUCE-directory>/modules

Note this part of the invoked `g++` command (I used the default name NewProject):
```
-I~/JUCE/modules -I/usr/include/freetype2 -c /home/xenox/NewProject/JuceLibraryCode/include_juce_audio_basics.cpp
```
This happens even if the JUCE directory is not named JUCE, and I specified the correct one.

**Comment by 0joshuaolson1** [comment]
The cbp file:

https://gist.github.com/0joshuaolson1/15f555a647e89aa4a9a1b0753484993a

**Comment by tpoole** [comment]
It appears that Code::Blocks fails to correctly expand any `~` symbols in paths. I've pushed a fix to the develop branch: https://github.com/WeAreROLI/JUCE/commit/39a6e9ea3134cf70ff799e485cd5da14a74a50ea.

Thank you for persisting!

**Comment by 0joshuaolson1** [comment]
Yay!
