### ISSUE TITLE
Wrong implementation of StringPairArray::operator==

### ISSUE THREAD

**Issue by martinfinke** [WeAreROLI/JUCE#280]
`StringPairArray::operator==` is currently implemented like this:

```cpp
for (int i = keys.size(); --i >= 0;)
    if (other [keys[i]] != values[i])
        return false;

return true;
```

With this implementation, an empty `StringPairArray` is equal to any other `StringPairArray` (but only if it's on the left side of the `==`). The documentation states that `operator==` returns "true only if the other array contains exactly the same strings with the same keys".

One solution is to add another `for` loop (before the final `return true`):

```cpp
for (const String& key : other.getAllKeys())
    if (!containsKey(key))
        return false;
```

Or you could implement it by emptying a set of string keys, etc.
Please fix this :) If you prefer a pull request, I'll make one.

**Comment by julianstorer** [comment]
Thanks, I'll take a look at that and push a fix to develop shortly..

**Comment by martinfinke** [comment]
Thanks!
