### ISSUE TITLE
AndroidManifest.xml: ability to customize the <supports-screens> element.

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#283]
As of now, the `supports-screens` element is populated with hard-coded attributes, see JUCE source [here](https://github.com/WeAreROLI/JUCE/blob/f08aa821b6be6a71f774bf7a163258ac0bbe0a22/extras/Projucer/Source/Project%20Saving/jucer_ProjectExport_Android.h#L1364).

This makes it so that, for example, the application distribution can not be limited to just "tablets", which Google suggests how to do here: [Declaring an App is Only for Tablets](https://developer.android.com/guide/practices/screens-distribution.html#FilteringTabletApps).

It would be handy to allow specifying a custom list of attributes (maybe as a raw String ?)

Regards

**Comment by lukaszkozakiewicz-roli** [comment]
This can be now achieved as mentioned in [here](https://forum.juce.com/t/breaking-change-introducing-custom-androidmanifest-xml-content-in-projucer-android-exporter/24740)

**Comment by mathieu-b** [comment]
@lukaszkozakiewicz-roli thanks for the heads up! This seems like an optimal choice: `AndroidManifest.xml` really has too many possible option to abstract them all away.
