### ISSUE TITLE
VS2015 debug build error

### ISSUE THREAD

**Issue by otristan** [WeAreROLI/JUCE#286]
Building latest develop trunk in Debug with VS2015 leads to this issue
juce_AudioFormatManager.cpp(43): error C2059: syntax error: '}'

Thanks !

**Comment by julianstorer** [comment]
The only thing on line 43 is a jassertfalse, there aren't any braces... Are you sure you've not accidentally typed into the file or something?

**Comment by julianstorer** [comment]
oh... This will be that stupid VC2015 compiler bug again.

Try putting braces around the for loop and it should be fine. I'll push that as a fix as well.

**Comment by otristan** [comment]
already did put the braces that indeed fixes the issue.
Just wanted to let you know :)
