### ISSUE TITLE
Typo in Android Exporter

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#298]
Here:
* https://github.com/WeAreROLI/JUCE/blob/eb0293a285b2725ca4e90137d26d0ab616df6f9e/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Android.h#L453
* https://github.com/WeAreROLI/JUCE/blob/eb0293a285b2725ca4e90137d26d0ab616df6f9e/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Android.h#L490

CONFIG**F**URATION instead of CONFIGURATION.

Cheers.

**Comment by tpoole** [comment]
Thanks for reporting.

Fixed in https://github.com/WeAreROLI/JUCE/commit/7867534ddf603468c78e7ffdba35c3f8dfd61511.
