### ISSUE TITLE
FR: Add URL source to XMLDocument

### ISSUE THREAD

**Issue by leehu** [WeAreROLI/JUCE#310]
Hi, we can currently construct an XMLDocument from a String or a File - would also be nice if we could give it a URL object and have it do its thing.

thx

**Comment by julianstorer** [comment]
Well, not really - reading a file or string is very simple, but a URL could take a long time, fail, need to be monitored for progress etc. I'd rather keep unrelated classes like XML and URL fully decoupled from each other.
