### ISSUE TITLE
Feature request: Lambda thread creating overload

### ISSUE THREAD

**Issue by lukashoror** [WeAreROLI/JUCE#312]
It's gonna be good to see these overloads for Lambda thread creating. Maybe It's not usual but it's useful and it's simple.

Thread *Thread::launch (std::function<void()> functionToRun);
Thread *Thread::launch (std::function<void()> functionToRun, const String& threadName);
Thread *Thread::launch (std::function<void()> functionToRun, int threadPriority);
Thread *Thread::launch (std::function<void()> functionToRun, const String& threadName, int threadPriority);

**Comment by julianstorer** [comment]
TBH I don't think the lambda thread idea is really very useful in the real world, so don't think it justifies adding extra overloads, because few people will end up actually using it in real code. It's just too unsafe to launch a thread without being able to stop it. We may try to come up with something better at some point, but in the meantime I'd suggest that if you need those overloads, you could just write yourself a free function to do the same thing, it wouldn't be very hard at all.

**Comment by lukashoror** [comment]
I respect your opinion, yes, maybe few people will use it. It's just a suggestion. But every framework should be robust as much as possible. If you have to write new code that is slightly different from framework's code, it's very bad especially in closed source frameworks. For the last few years I've been working with frameworks where I haven't missed anything and I didn't have to do anything extra. Juce is no exception, it's great, but rarely I find something that stops me for several hours.

Lambda, especially lambda threads are often used in C# and they make coding much easier because you don't have to write new class derived from Thread to override run() method. It's slave labor and it's not effective (and every programmer is little bit lazy). And if the Thread::lambda returns Thread instance, you can control the thread with some restrictions. 

One disadvantage of C++ is there is no extending of existing code (like C# does), so I don't know, how can I extend class Thread without modifying Juce source code? I can't to change Juce code and I don't want to create some extra namespace or extra class, because it comes with different name and mainly it is new discovery of the wheel.

**Comment by julianstorer** [comment]
It's because it's inherently not robust that I'd discourage you from just launching lambdas like this! I think there are threads about this on the forum, which would be a better place to continue the discussion if you want to explore it more.
