### ISSUE TITLE
CLion CMakeLists does append ".a" for static library target

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#315]
To reproduce:

- Create a static library project in the projucer
- Add a CLion exporter and export a CMakeLists.txt
- Run CMake on the generated CMakeLists.txt

Expected:

- A static library with ".a" suffix is created

Actual:

- A static library is created but no suffix is added

**Comment by McMartin** [comment]
On which platform do you have that problem? Linux or Mac?

**Comment by tpoole** [comment]
Thank you for reporting. We'll fix this shortly.
