### ISSUE TITLE
Standalone Plugin cannot receive Midi

### ISSUE THREAD

**Issue by MrRandomTree** [WeAreROLI/JUCE#316]
Reproduce:
Create a new Plugin with the Projucer. Open in IDE. Debug Standalone. Click Options and select a Midi Input Device. Press any Key on the Midi Device. An assertion is triggered in:
"juce_MidiMessageCollector.cpp" Line 51

Expected Behavior:
Midi is passed on to Process Block.

OS: Win10
Architecture: 64 bit
IDE: Visual Studio 2017

**Comment by ed95** [comment]
This has been fixed in the latest version of JUCE.
