### ISSUE TITLE
Can anyone check this?

### ISSUE THREAD

**Issue by Remberg** [WeAreROLI/JUCE#317]
Hey guys, i think something's wrong there. Can anyone check this?
https://github.com/WeAreROLI/JUCE/blob/2206fae758e1570ba384f264b78df8ed950de146/modules/juce_audio_basics/effects/juce_IIRFilter.h#L206

OS: Win10
Architecture: 64 bit
IDE: Visual Studio 2017

**Comment by julianstorer** [comment]
It might help if you explained what you think is wrong? That line deliberately disables the assignment operator, because copying from a stateful filter would make little sense and wouldn't be thread-safe.

**Comment by Remberg** [comment]
ah OK sorry, i did not know that's on purpose.

**Comment by cesaref** [comment]
I think this is one of the problems with that old style, hiding methods to make them inaccessible. Jules, are things c++11 enough now in the code base to move to an explicit '= delete' or does JUCE require platform support where this isn't available? It would be a good idea to avoid such confusion.

**Comment by julianstorer** [comment]
Yes, we've finally been able to use  = delete recently, and have gradually updated classes as we noticed them. Will update this one too!
