### ISSUE TITLE
Juce audio plugin demo hangs or crashes Digital Performer when closing plugin window while previewing

### ISSUE THREAD

**Issue by KoenTanghe** [WeAreROLI/JUCE#321]
Note: I had this with my own plugin, which is using the before-last commit on the master branch, but this apparently happens with the Juce audio plugin demo as well, also with the latest commit on the develop branch:

  **1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code**

a. Build the Juce audio plugin demo from the latest develop branch (a2bbd992342324d676bb68fc3fdb28c4f7965d0b). I also rebuilt the ProJucer first, opened and re-saved the .jucer project before I built the plugin.
b. open a project in Digital Performer (I used the demo project that MOTU offers for download)
c. select a audio clip on an audio track, right-click, select "Apply plugin..." and choose the Juce demo plugin
d. click the Preview button under the plugin's GUI in the plugin window that appears
e. while still previewing, close the plugin window
--> on Windows, DP hangs (you can't do anything any longer and the only way to quit it is by killing the program in the task manager)
--> on MacOS,  DP crashes

  **2) the expected behaviour**

The plugin window should just close, and the host should continue to work normally.

  **3) the operating system**

Windows 10 64-bit (all latest updates)
MacOS 10.12.6 Sierra (all latest updates)

  **4) the architecture (32-bit or 64-bit)**

64-bit plugin, 64-bit DP

  **5) a stack trace - if the bug causes a crash**

not available (hangs on Windows + on Mac I didn't get a stack trace IIRC, but I could check again)

  **6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable**

VST2 on Windows, VST2 or AU on MacOS

  **7) which DAW you observed the bug in - if applicable**

MOTU Digital Performer 9.5 (latest available version, running in demo mode)

Cross-reference to forum topic: https://forum.juce.com/t/juce-audio-plugin-demo-hangs-or-crashes-digital-performer-when-closing-plugin-window-while-previewing/25598

**Comment by KoenTanghe** [comment]
As mentioned in the forum:
Today, I also tried this "preview" functionality in DP 9.5 with one of their own MAS plugins "Auto-pan" and the same thing happened: hang on Windows10 and crash on MacOS.
So, this indicates that this might not be a Juce-related issue after all.
Will see if I can reach someone at MOTU about this.

**Comment by julianstorer** [comment]
Ok, thanks, that does sound pretty conclusive! I'll close this bug report for now, but please re-open if it turns out there's something we need to do to fix it.
