### ISSUE TITLE
dsp::Matrix doesn't allow matrix multiplication if matrices have different outer dimensions

### ISSUE THREAD

**Issue by thomasdeppisch** [WeAreROLI/JUCE#326]
Hi,

currently, matrix multiplication with dsp::Matrix (`Matrix<ElementType>::operator* (const Matrix<ElementType>& other) const`) is only allowed if the matrices have the same inner AND outer dimensions.
This is accomplished by a jassert: `jassert (other.getNumRows() == p && n == m);`
So multiplication of two matrices _n x p_ and _l x m_ is only possible if _l == p_ and _n == m_.

For a valid matrix multiplication in the mathematical sense only the inner dimensions have to be the same. Changing the jassert to `jassert (other.getNumRows() == p);` allows mathematically valid multiplications. So, if I understand correctly the jassert should be changed the way I described.

Thanks!

**Comment by tpoole** [comment]
Yes, you're right. I'm not sure how that assertion got there...

We'll get this fixed - thanks for reporting.
