### ISSUE TITLE
JACK client name

### ISSUE THREAD

**Issue by umlaeute** [WeAreROLI/JUCE#331]
when compiling a plugin as a standalone with JACK support (on linux), the application will show up (in jackd) with a jack client name `JUCEJack`.

This is probably a nice client name when debugging JUCE's jack support, but unfortunately it fails the real world usability test.
E.g. running a few different JUCE standalone applications (e.g.: a compressor,  an ambisonics encoder, a reverb and an ambisonics decoder) will give me the following jack clients:

- `JUCEJack`
- `JUCEJack-01`
- `JUCEJack-02`
- `JUCEJack-03`

Instead i would have expected a client name based on the actual plugin name, e.g.
- `FooCompressor`
- `AmbisonicsEncoder5`
- `AmbiReverb`
- `AmbisonicsDecoder5`

**Comment by umlaeute** [comment]
Something like the following should fix the problem (please note, that this is totally untested)

~~~diff
--- a/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp
+++ b/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp
@@ -104,7 +104,11 @@ namespace
 
 //==============================================================================
 #ifndef JUCE_JACK_CLIENT_NAME
- #define JUCE_JACK_CLIENT_NAME "JUCEJack"
+ #ifdef JucePlugin_Name
+ # define JUCE_JACK_CLIENT_NAME JucePlugin_Name
+ #else
+ # define JUCE_JACK_CLIENT_NAME "JUCEJack"
+ #endif
 #endif
~~~

**Comment by umlaeute** [comment]
ping.

(is there any specific reason to ignore this, like lack of interest in supporting JACK, or is this just bad luck?)

**Comment by McMartin** [comment]
If you want to get extra visibility on this issue you should consider creating a thread on the JUCE forum: https://forum.juce.com/

**Comment by ed95** [comment]
Closed in [351](https://github.com/WeAreROLI/JUCE/pull/351) - thanks!
