### ISSUE TITLE
2 * 3 * 5 = 10 ?!?

### ISSUE THREAD

**Issue by yairchu** [WeAreROLI/JUCE#335]
(Originally reported in the forum as "[dsp::ProcessorChain only works with ProcessContextReplacing?](https://forum.juce.com/t/dsp-processorchain-only-works-with-processcontextreplacing/25726)")

`dsp::ProcessorChain` gives some very surprising results:

    // single sample and channel buffers.
    AudioBuffer<double> input (1, 1), output (1, 1);

    // initialize input to 2
    input.setSample (0, 0, 2.0);

    // multiply it by 3 and then by 5
    ProcessorChain<Gain<double>, Gain<double> > chain;
    chain.get<0>().setGainLinear (3.0);
    chain.get<1>().setGainLinear (5.0);

    // but use a non-replacing context
    chain.prepare ({ 44100.0, 256, 1} );
    AudioBlock<double> inputBlock (input), outputBlock (output);
    ProcessContextNonReplacing<double> ctx (inputBlock, outputBlock);
    chain.process (ctx);

    cout << output.getSample (0, 0) << endl;

This prints out the result of `2*3*5`, which is `10` according to `dsp::ProcessorChain` but the more "standard" result is `30`...

**Comment by tpoole** [comment]
Fixed in https://github.com/WeAreROLI/JUCE/commit/e79663e5f5fa789ec99e96bcbf07a5cbadbf71f8.
