### ISSUE TITLE
juce::AlertWindow - items added with addTextEditor not displayed if run with showMessageBoxAsync

### ISSUE THREAD

**Issue by sseyod** [WeAreROLI/JUCE#337]
Using the tip of JUCE master.

I've done quite a few experiments using juce::AlertWindow - this  works fine in Async mode using showMessageBoxAsync().

However, if I use it in combination with addTextEditor(), the text editor is displayed *only* when using runModalLoop() ...!

Tested (only) with iOS (not using native alert Windows).

Of course, it'd be nice if you had a static method to show a simple text entry alert, natively (or otherwise), for each platform. :)

Hoping this feedback helps... Pete

**Comment by ed95** [comment]
`showMessageBoxAsync()` is just a static helper method for easily creating and showing a simple `AlertWindow`. If you want to have a more complicated window, with a `TextEditor` for example, then you should create an instance of `AlertWindow`, call `addTextEditor()` on it and then show it asynchronously by calling `enterModalState()` on the object.

**Comment by sseyod** [comment]
Hi Ed, thanks for explaining - I didn't realise that from the docs!

Best wishes, Pete

**Comment by sseyod** [comment]
Here is some example code, in case it helps anybody...

```
  std::function<void(const juce::String&)> theCompletion; // Implemented elsewhere...

  juce::AlertWindow *w = new juce::AlertWindow(title, "", juce::AlertWindow::NoIcon);
  w->addTextEditor("text", defaultValue, "Enter value", false);
  w->addButton("OK", 1, juce::KeyPress(juce::KeyPress::returnKey, 0, 0));
  w->addButton("Cancel", 0, juce::KeyPress(juce::KeyPress::escapeKey, 0, 0));
  
  auto alertLambda = ([w, theCompletion](int result) {
    
    if (result == 1) {
      auto result = w->getTextEditorContents("text");
      theCompletion(result);
    } else {
      auto result = juce::String("");
      theCompletion(result);
    }
  });
  auto callback = juce::ModalCallbackFunction::create(alertLambda);
  
  // Run asynchronously
  w->enterModalState(true, callback, true); // true - take keyboard focus, handler, true means - delete when dismissed
```
