### ISSUE TITLE
Is there a removeMeterListener line missing?

### ISSUE THREAD

**Issue by remberg** [WeAreROLI/JUCE#343]
https://github.com/WeAreROLI/JUCE/blob/f204a99c6f0a058b90a1bff3c9241de7b70e5af1/examples/PlugInSamples/InterAppAudioEffect/Source/IAAEffectEditor.h#L98

I get an access violation error on closing the InterAppAudioEffect demo.
I add this lines and it works fine but I dont know if I'm right.

IAAEffectEditor::~IAAEffectEditor()
    {
        processor.removeMeterListener (*this);
    }

**Comment by tpoole** [comment]
That looks like a bug to me; we'll get that sorted. Thank you for reporting!
