### ISSUE TITLE
Missing build targets in examples/ and extras/

### ISSUE THREAD

**Issue by 0joshuaolson1** [WeAreROLI/JUCE#345]
Requested in https://github.com/WeAreROLI/JUCE/issues/323#issuecomment-352848210. I included all that I wasn't sure wouldn't apply:
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/DSP%20module%20plugin%20demo/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/ComponentTutorialExample/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PlugInSamples/Arpeggiator/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PlugInSamples/GainPlugin/Build
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PlugInSamples/MultiOutSynth/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PlugInSamples/NoiseGate/Builds
  - LinuxMakefile
  - VisualStudio2013
  - Android
  - iOS
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/OpenGLAppExample/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/AudioAppExample/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/AnimationAppExample/Builds
  - LinuxMakefile
  - VisualStudio2013
  - VisualStudio2015
  - Android
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/SimpleFFTExample/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PluckedStringsDemo/Builds
  - LinuxMakefile
  - VisualStudio2015
  - Android
  - iOS
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/DSPDemo/Builds
  - VisualStudio2013
  - VisualStudio2015
  - Android
  - iOS
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/OSCMonitor/Build
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/MPETest/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/PlugInSamples/Surround/Builds
  - VisualStudio2013
  - Android
  - iOS
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/PushNotificationsDemo/Builds
  - LinuxMakefile
  - VisualStudio2013
  - VisualStudio2017
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/BouncingBallWavetableDemo/Builds
  - VisualStudio2015
  - Android
  - iOS
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/HelloWorld/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/BLOCKS/BlocksSynth/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/BLOCKS/BlocksDrawing/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/BLOCKS/BlocksMonitor/Builds
  - VisualStudio2013
  - Android
- https://github.com/WeAreROLI/JUCE/tree/develop/extras/AudioPerformanceTest/Builds
  - VisualStudio2013
  - VisualStudio2017
- https://github.com/WeAreROLI/JUCE/tree/develop/extras/binarybuilder/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/extras/UnitTestRunner/Builds
  - VisualStudio2013
  - VisualStudio2015
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/audio%20plugin%20demo/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/OSCSender/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/OSCReceiver/Builds
 https://github.com/WeAreROLI/JUCE/tree/develop/examples/MidiTest/Builds
  - VisualStudio2013
- https://github.com/WeAreROLI/JUCE/tree/develop/examples/NetworkGraphicsDemo/Builds
  - VisualStudio2015
______
Not that I want the feature, but is InAppPurchases [unsupported on Windows](https://github.com/WeAreROLI/JUCE/blob/4c44d96fdf70448b3386414543c668bcdc823d8a/modules/juce_product_unlocking/in_app_purchases/juce_InAppPurchases.cpp) because of Windows 7?

I didn't look at https://github.com/WeAreROLI/JUCE/tree/develop/extras/BLOCKS/standalone_sdk

**Comment by ed95** [comment]
Closing this as the JUCE examples/ and extras/ directories have changed considerably in JUCE 5.3.0.
