### ISSUE TITLE
ios 11 devices crashing with CRASHING_DUE_TO_PRIVACY_VIOLATION

### ISSUE THREAD

**Issue by sigpoggy** [WeAreROLI/JUCE#346]
1) To reproduce the problem, create a new "Audio Application" with Projucer 5.2.0 and export to ios. Then run xcode 9.2 to compile and run on an ios 11.2 device (tried iPad air, iPad pro 10.5, iPad pro 12.9, iphone 6s+). Note that running on the simulator will work ok for the same device/ios configs.  Also, devices with ios 9.3 worked ok.
 
  2) Upon the app starting up on the device, it immediately crashes.

  3) Host system: MacOS; build target system: ios 9.0 ; test devices system: ios 11.2

  4) the architecture 64 bit

  5) stack trace: 
Thread 4 Queue : com.apple.root.default-qos (concurrent)
#0	0x000000018150b048 in __abort_with_payload ()
#1	0x0000000181505bdc in abort_with_payload_wrapper_internal ()
#2	0x0000000181505c08 in abort_with_payload ()
#3	0x0000000184488980 in __CRASHING_DUE_TO_PRIVACY_VIOLATION__ ()
#4	0x00000001844888a0 in __TCCAccessRequest_block_invoke.77 ()
#5	0x000000018448c13c in __tccd_send_block_invoke ()
#6	0x0000000181659d44 in _xpc_connection_reply_callout ()
#7	0x0000000181659c80 in _xpc_connection_call_reply_async ()
#8	0x0000000105da9aa4 in _dispatch_client_callout3 ()
#9	0x0000000105dc3cd4 in _dispatch_mach_msg_async_reply_invoke ()
#10	0x0000000105db51c4 in _dispatch_queue_override_invoke ()
#11	0x0000000105dba9d0 in _dispatch_root_queue_drain ()
#12	0x0000000105dba6f4 in _dispatch_worker_thread3 ()
#13	0x000000018161f06c in _pthread_wqthread ()
#14	0x000000018161eb6c in start_wqthread ()
Enqueued from com.apple.libdispatch-manager (Thread 3) Queue : com.apple.libdispatch-manager (serial)
#0	0x0000000105dc18f8 in _dispatch_mach_reply_merge_msg ()
#1	0x0000000105dc6dec in _dispatch_event_loop_merge ()
#2	0x0000000105dbfbfc in _dispatch_kevent_worker_thread ()
#3	0x000000018161eed8 in _pthread_wqthread ()
#4	0x000000018161eb6c in start_wqthread ()

*** Problem occurs on development branch as well.

**Comment by ed95** [comment]
You'll need to enable microphone access in the iOS exporter settings of the Projucer:

<img width="1240" alt="screen shot 2018-01-23 at 09 00 26" src="https://user-images.githubusercontent.com/6862971/35266691-eb09e0a2-001b-11e8-86ff-5fd57b5f7ffc.png">
