### ISSUE TITLE
allow symlinks when generating doxygen documentation

### ISSUE THREAD

**Issue by umlaeute** [WeAreROLI/JUCE#349]
I tried to generate the API documentation with doxygen (from git-clone of JUCE), and ended up with a rather empty directory.
After investigation, it turned out, that Doxygen is looking for the header files in a `build/` directory, which I don't have.
A quick workaround would be to symlink the `modules/` directory to the ominous `build/` directory, but this fails, since the Doxyfile explicitly forbids to follow symlinks.

Since I couldn't think of a reason where this makes sense, I propose the following change:

~~~diff
--- juce.orig/doxygen/Doxyfile
+++ juce/doxygen/Doxyfile
@@ -862,7 +862,7 @@
 # from the input.
 # The default value is: NO.
 
-EXCLUDE_SYMLINKS       = YES
+EXCLUDE_SYMLINKS       = NO
 
 # If the value of the INPUT tag contains directories, you can use the
 # EXCLUDE_PATTERNS tag to specify one or more wildcard patterns to exclude
~~~

This allows me to generate the API documentation with something like:

~~~sh
ln -s modules build
doxygen doxygen/Doxyfile
~~~

**Comment by tpoole** [comment]
Have you looked at the README?

You need to use the Makefile in that directory to build the docs - we do some preprocessing of the source code to add Doxygen groups to the source code, where the preprocessed source is placed in the `build` directory.

**Comment by umlaeute** [comment]
🤦‍
