### ISSUE TITLE
[Projucer] OSX Export : "Extra frameworks" should allow other extensions (at least dylib)

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#358]
When using libraries like libusb, xcode needs to add "libusb-1.0.0.dylib" to the frameworks.
It would possible to add this via the Projucer using the "Extra frameworks" section, but since its extensions is not ".framework", Projucer adds it when saving the project, so it becomes impossible to add other frameworks than ".framework" files.

Pull request would seem overkill for this, but here is my fix proposal (tested and works for on my OSX VM and on Travis) :
in file **jucer_ProjectExport_Xcode.h**  line 2707 :

```
   if (! path.endsWithIgnoreCase (".framework") && !path.endsWithIgnoreCase(".dylib"))
            path << ".framework";
```

It could be more flexible than that but at least dylib which are very common would be supported.

**Comment by McMartin** [comment]
If you want to add a library, such as libusb, you should add it to the `Externals Libraries to Link` section. The `Extra Frameworks` section is for frameworks only.

**Comment by benkuper** [comment]
Thanks for the quick reply, i already tried it and saw other people try and
fail as well.
The Externals libraries to link doesn't add the "libusb-1.0.dylib" file in
the "frameworks" section of the build phases in xcode and i couldn't manage
to link it any other way. Actually i think i even saw an official tutorial
for using libusb with xcode mentionning to do this (including the dylib in
the frameworks section).

Anyway, as it is allowed by xcode to include other files extensions in this
section, don't you think the Projucer should allow for other extensions as
well ? automatically adding the .framework extension if there is no one
mentionned can be nice, but it shouldn't create a such a limitation imho.

**Comment by tpoole** [comment]
I have no problems linking with libusb using the `External Libraries to Link` field of the Projucer, can you provide a bare bones example of it failing?

    brew install libusb

Create a new project in the Projucer:

- External Libraries to Link: usb-1.0
- Header search paths: /usr/local/include
- Extra library search path: /usr/local/lib

Then:

    #include "libusb-1.0/libusb.h"

    libusb_context *context = NULL;
    libusb_init(&context);

**Comment by benkuper** [comment]
yes sorry i managed to do it finally.

However i need the generated .app to be autonomous as i want people to be able to download it and use it without having to install libusb by themselves. I managed to do it by adding the dylib as a xcode resource in the projucer files and change the dylib link path using install_name_tool to set it as "@executable_path/../Resources" so the app would not search for the dylib at  /usr/local/Cellar/... at runtime.
Do you know a more "proper" way to use dylib and build a fully portable .app ?

Thanks

**Comment by tpoole** [comment]
Not using a dylib.

Why not statically link `libusb-1.0.a`?

**Comment by benkuper** [comment]
oh ok this is a static lib, i'm really not familiar with how osx handles libraries and i find online resources quite confusing.
Thanks !

**Comment by benkuper** [comment]
Actually now i remember that i tried that and i didn't find a way to link the .a file, it's still looking for the dylib and if i put libusb-1.0.a in the external libraries to link, it says it can't find it (the library search paths are correct)
