### ISSUE TITLE
Bug in Projucer when Linking External Libraries

### ISSUE THREAD

**Issue by tschutli** [WeAreROLI/JUCE#360]
I think I have found a bug in the Projucer. When I add an external library in the Projucer, I get an error in Xcode that the library could not be found. The following message is printed.

`ld: library not found for -l/path/to/lib/libboost_system-mt.a`

It seems like there is a space missing between the -l flag and the path.

**Comment by tpoole** [comment]
When you use the "External Libraries to Link" field you should only enter the undecorated library name `boost_system-mt`, and then add `/path/to/lib/` to the "Extra library search paths" field.
