### ISSUE TITLE
Audio:Recording demo on Android isn't working

### ISSUE THREAD

**Issue by jkoutavas** [WeAreROLI/JUCE#361]
When I run the Android target of the JuceDemo v5.2.1 app on an emulator, or on actual hardware, the Audio:Recording demo isn't working. I hit the "Record" button, make some sounds, see the real-time feedback of the wave form, but when I hit stop, no file is created. Using Android 7.1.1, API 25.

This same demo is working fine on iOS and macOS.

There are no commits in the repo past the 5.2.1 tag that may be of any aid to me.

**Comment by ed95** [comment]
Can you try this with the latest version of JUCE? We have updated all of the demos and this should be fixed.

**Comment by jkoutavas** [comment]
Yes, it is fixed now in 5.3.0.

Thank you.
