### ISSUE TITLE
Problems with AudioRecordDemo and AudioPlaybackDemo

### ISSUE THREAD

**Issue by jkoutavas** [WeAreROLI/JUCE#365]
Using JUCE 5.3.0 DemoRunner. iOS 9 deployment, ASDK 27 deployment.

I am able to successfully record audio using both the iOS and Android AudioRecordingDemo on iOS and Android simulators, but am not able to play these saved files back using the AudioPlaybackDemo on either the simulators or an Android device. Just on iOS devices. The file chooser isn't returning a file.

Also, AudioRecordDemo does not complete a file save on Android.

**Comment by ed95** [comment]
It looks like this has been fixed as of JUCE 5.4.5. Feel free to re-open the issue if not.
