### ISSUE TITLE
ListBox/Viewport bug (description, candidate solution)

### ISSUE THREAD

**Issue by sseyod** [WeAreROLI/JUCE#366]
Hi!

I have finally tracked-down an serious ListBox/Viewport bug that has been bugging me for a few months. I thought I should share my findings, and my candidate solution.

Configuration:
- create a Component with an embedded ListBox, which doesn't take-up the full screen
  (I'm not sure if this is significant or not)
- make sure the ListBox supports drag scrolling
- drag around, it works well.

The problem:
- mobile (e.g. iOS Simulator): drag around, but do quickly, and be sure to sometimes release the mouse outside of the ListBox onto another component.
- desktop: flicking the mouse wheel around over the listbox (to scroll it) and combine with dragging, in quite quick succession.
- if you're unlucky, the list box no longer scrolls by dragging; you have to use the scrollbar; not good :)

My candidate solution:
- I have modified juce_Viewport.cpp, to add the following:
```C++
  void mouseExit (const MouseEvent& e) override
  {
    if (doesMouseEventComponentBlockViewportDrag (e.eventComponent))
      isViewportDragBlocked = false;
    
    if (numTouches == 0) {
      // printf ("MPC mouseExit - numTouches already zero\n");
      return;
    }

    printf ("MPC mouseExit - WARNING!!! - numTouches=%d!\n", numTouches);
    
    if (--numTouches <= 0)
    {
      printf ("MPC mouseExit - WARNING!!! - numTouches now=%d!\n", numTouches);

      offsetX.endDrag();
      offsetY.endDrag();
      isDragging = false;
      numTouches = 0;
    }
  }
```
Summary:
- can you please find a way to reproduce this, and apply a fix to the repo?
- that will remove the requirement for me to locally patch my Juce source code :)

Pete

**Comment by sseyod** [comment]
Hi!

I've just tested with the latest Juce master branch (5.3.0), and the problem still exists.

It happens most often in large ListBoxes, so I wonder if it is somehow timing related.

Anyhow: the fix is really simple, and the latest patch is as follows - simply add the mouseExit method as below.

```c++
    void mouseExit (const MouseEvent& e) override
    {
      if (numTouches == 0) {
        #ifdef _DEBUG
        printf ("DEBUG: MPC mouseExit - ok, numTouches already zero\n");
        #endif // _DEBUG
        return;
      }
      
  #ifdef _DEBUG
      printf ("DEBUG: MPC mouseExit - WARNING!!! - numTouches=%d!\n", numTouches);
  #endif // _DEBUG
      
      if (--numTouches <= 0)
      {
  #ifdef _DEBUG
        printf ("DEBUG: MPC mouseExit - WARNING!!! - numTouches now=%d!\n", numTouches);
  #endif // _DEBUG
        
        offsetX.endDrag();
        offsetY.endDrag();
        isDragging = false;
        numTouches = 0;
      }
    }
```

**Comment by ed95** [comment]
Closing this now. Discussion is [here](https://forum.juce.com/t/listbox-viewport-bug-description-candidate-solution/26909)
