### ISSUE TITLE
Projucer overwrites AppConfig.h when it shouldn't

### ISSUE THREAD

**Issue by jpcima** [WeAreROLI/JUCE#377]
When I save the project, AppConfig.h will be regenerated despite not having touched any project setting.
It results in make rebuilding systematically the entire JUCE modules.
This happens on 64 bit Linux.

I did my own trace in JUCE code and I a semi-explanation as of why this happens.
[trace.txt](https://github.com/WeAreROLI/JUCE/files/1908537/trace.txt)
I inserted this code in **overwriteFileWithNewDataIfDifferent**, and file attached was the output.

```
        fprintf(stderr, "File %s is %s\n",
                file.getFileName().toRawUTF8(),
                sameContents ? "identical" : "different");
```

You can see from trace that AppConfig.h was overwritten twice in the process of saving.
So we have a succession of saved files which I can denote as 1->2->3. The original (1) and final (3) are identical. The intermediate one (2) however, lacks the "Audio plugin settings" at the bottom.

I saved these two files (2) and (3) and attach them to this issue report. You can diff these files and see yourself.
[AppConfig1.txt](https://github.com/WeAreROLI/JUCE/files/1908561/AppConfig1.txt)
[AppConfig2.txt](https://github.com/WeAreROLI/JUCE/files/1908562/AppConfig2.txt)

The source of the project is accessible [here](https://github.com/jpcima/ADLplug).

**Comment by McMartin** [comment]
I spent some time figuring out what was going on in `ProjectSaver::save()`:

```
  jucer_ProjectSaver.h: 96    writeAppConfigFile()
  jucer_ProjectSaver.h:516        writeAppConfig()
  jucer_ProjectSaver.h:507            if (extraAppConfigContent.isNotEmpty()) // empty
  jucer_ProjectSaver.h:508                out << newLine << extraAppConfigContent.trimEnd() << newLine;
  jucer_ProjectSaver.h:516        saveGeneratedFile()
  jucer_ProjectSaver.h: 97    writeBinaryDataFiles()
  jucer_ProjectSaver.h: 98    writeAppHeader()
  jucer_ProjectSaver.h: 90    writeModuleCppWrappers()
  jucer_ProjectSaver.h:100    writeProjects()
jucer_ProjectSaver.cpp:195      writePluginCharacteristicsFile()
jucer_ProjectSaver.cpp:151          setExtraAppConfigFileContent()
  jucer_ProjectSaver.h:196                extraAppConfigContent = content; // empty -> non-empty
  jucer_ProjectSaver.h: 96    writeAppConfigFile()
  jucer_ProjectSaver.h:516        writeAppConfig()
  jucer_ProjectSaver.h:507            if (extraAppConfigContent.isNotEmpty()) // non empty
  jucer_ProjectSaver.h:508                out << newLine << extraAppConfigContent.trimEnd() << newLine;
  jucer_ProjectSaver.h:516        saveGeneratedFile()
```

Quite strangely, `writePluginCharacteristicsFile()` is called for each exporter. This means that the last exporter will be the last one to override `extraAppConfigContent` and "win".

Applying the following patch "fixes" the problem, however I am not sure whether it's 100% correct to do that:
```diff
diff --git a/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.cpp b/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.cpp
index d5075906a..4d8d9a483 100644
--- a/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.cpp
+++ b/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.cpp
@@ -191,9 +191,6 @@ void ProjectSaver::writeProjects (const OwnedArray<LibraryModule>& modules, cons
                     for (auto& module: modules)
                         module->addSettingsForModuleToExporter (*exporter, *this);

-                    if (project.getProjectType().isAudioPlugin())
-                        writePluginCharacteristicsFile();
-
                     generatedFilesGroup.sortAlphabetically (true, true);
                     exporter->getAllGroups().add (generatedFilesGroup);
                 }
diff --git a/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.h b/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.h
index f9067a0c8..3f6b2f8b3 100644
--- a/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.h
+++ b/extras/Projucer/Source/ProjectSaving/jucer_ProjectSaver.h
@@ -93,6 +93,9 @@ public:

             auto projectRootHash = project.getProjectRoot().toXmlString().hashCode();

+            if (project.getProjectType().isAudioPlugin())
+                writePluginCharacteristicsFile();
+
             writeAppConfigFile (modules, appConfigUserContent);
             writeBinaryDataFiles();
             writeAppHeader (modules);
```

@ed95 @hogliux @julianstorer @tpoole is my patch sensible or am I missing something?

**Comment by jpcima** [comment]
Correct or not, I confirm it works after the patch. :+1: 
It is a terribly irritating bug. Thanks for figuring out the problem so quickly.

**Comment by McMartin** [comment]
@ed95 what you pushed (https://github.com/WeAreROLI/JUCE/commit/193a47c10b553d69537a2d431a15374ad7886521) is not my patch, and doesn't fix the reported problem. In what you pushed, `extraAppConfigContent` is still set between the two calls to `writeAppConfigFile()`, thus `AppConfig.h` will be different and written twice.

**Comment by ed95** [comment]
@McMartin  Sorry, I misunderstood the problem and assumed that the issue was the multiple calls to `writePluginCharacteristicsFile()`. [6dbcfbf](https://github.com/WeAreROLI/JUCE/commit/6dbcfbf6e577609bd3ba2f663edd390798ee11e1) ensures that `AppConfig.h` will only be written once, and won't be overwritten if there are no changes.

**Comment by jpcima** [comment]
@ed95 I tried with the new develop branch. No problem now. Thanks.
