### ISSUE TITLE
read audio file and direct write to new file but the sound not same as original

### ISSUE THREAD

**Issue by jucehub** [WeAreROLI/JUCE#383]
1) My process 

1.1 read wav file from file chooser

1.2 create fileoutputstream and new block to keep data readed from reader->read()

1.3 write it to new file (read 1024 sample per block and write it to new file every loop ) 

1.4 after write finished new sound have more speed than original and have some noise and sound frequency maybe half of original file

  3) windows  10
  4) 64 bit
sorry  for my bad english and thank you for answer.

![capture](https://user-images.githubusercontent.com/35908909/39172686-b29c9586-47cc-11e8-91fc-8470203bb1fb.PNG)
![capture2](https://user-images.githubusercontent.com/35908909/39172689-b556334a-47cc-11e8-901b-a029d87adf9c.PNG)
![capture3](https://user-images.githubusercontent.com/35908909/39172691-b76ac150-47cc-11e8-9791-82a52b6871c1.PNG)
![capture4](https://user-images.githubusercontent.com/35908909/39172694-b96c9c44-47cc-11e8-9ac3-161e39c1fad4.PNG)

**Comment by julianstorer** [comment]
The github issue tracker is for reporting actual _bugs_ in juce. For this kind of help request, please post on the juce forum and we can help you there!
