### ISSUE TITLE
Request: make sendPropertyChangeMessage *excluding listener* public

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#385]
In the public interface of `ValueTree` we have `setProperty()` and `setPropertyExcludingListener()`. The ability to exclude listeners is useful.

It would be great if the ability to call `sendPropertyChangeMessage()` excluding listeners was also exposed publicly.

This would entail adding the following to ValueTree.h...

`void sendPropertyChangeMessage (const Identifier& property, ValueTree::Listener* listenerToExclude = nullptr);`

**Comment by julianstorer** [comment]
Would prefer not to open up implementation details like that without a really solid use-case.. What are you trying to achieve?

**Comment by julianstorer** [comment]
Sorry, I really don't like the idea that it could be used to send a fake change message when nothing has changed. If you need to trigger a forced update under certain circumstances then that's probably something that should happen via other means than the ValueTree

**Comment by jamiebullock** [comment]
In practical terms a use case for fake changes would be a property the stores the is selected in a combo box, and the combo is used for switching between presets. A user may select a preset then manually change some parameters. Re-selecting the same preset from the combo I would expect the preset to be re-applied.

Handling this by responding to changes in a ValueTree is convenient because it gives only one control path for selecting a different menu item or selecting the same one again.

The principle applied to any property the causes other properties or parameters to be updated

**Comment by julianstorer** [comment]
TBH I'm not sure why sendPropertyChangeMessage is public..! It probably shouldn't be. 

And sorry, but I just don't buy your argument that re-triggering GUI state is a good use case for this - if your GUI has no other way of forcing it to refresh itself based on the current state then it's not the responsibility of the ValueTree to fix that. Normally I'd expect to have some kind of GUI refresh functionality that would be called in response to the ValueTree's listener callback, but which could also be called directly.

**Comment by jamiebullock** [comment]
OK, fair enough. Thanks for explaining.
