### ISSUE TITLE
Linux Xrandr problem in transition from ScopedPointer to std::unique_ptr

### ISSUE THREAD

**Issue by jpcima** [WeAreROLI/JUCE#389]
On Linux X11, a mismatched malloc-delete is detected in the address sanitizer.

It follows the transition to `std::unique_ptr` https://github.com/WeAreROLI/JUCE/commit/ab863a6dc2aa84f3f97502eb6358348e6cb86f23, which uses `default_delete` instead of the appropriate deleter for these Xrandr types: `XRRScreenResources` `XRROutputInfo` `XRRCrtcInfo`

Before, `ScopedPointer` would pick up the template specializations of `ContainerDeletePolicy` which are located in the same file. For the same effect, these instanciations of `unique_ptr` should have their matching deleter.

https://github.com/WeAreROLI/JUCE/blob/ab863a6dc2aa84f3f97502eb6358348e6cb86f23/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp#L1172

https://github.com/WeAreROLI/JUCE/blob/ab863a6dc2aa84f3f97502eb6358348e6cb86f23/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp#L1193

https://github.com/WeAreROLI/JUCE/blob/ab863a6dc2aa84f3f97502eb6358348e6cb86f23/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp#L1200

**Comment by julianstorer** [comment]
Thanks for the heads-up, I'll sort that out and push a fix today!
