### ISSUE TITLE
Cannot build for Windows with Code::Blocks - missing REPLACEFILE_IGNORE_ACL_ERRORS

### ISSUE THREAD

**Issue by Spiffyk** [WeAreROLI/JUCE#393]
When I try to cross-compile my VST 32-bit plugin for Windows using Code::Blocks on Manjaro Linux with MinGW (but I did try on a Windows VM, too - same result), I get the following error:

```
(...)/juce/modules/juce_core/native/juce_win32_Files.cpp:267:62: error: ‘REPLACEFILE_IGNORE_ACL_ERRORS’ was not declared in this scope
```

I tried commenting out the `REPLACEFILE_IGNORE_ACL_ERRORS` which did help but I'm guessing that is not the proper way to fix it and might cause further problems down the road.

I also tried the `develop` branch on Linux, nothing changed.

**Comment by julianstorer** [comment]
Ta, I'll push something to develop to fix this later today
