### ISSUE TITLE
JUCE's develop branch is no longer GPLv3

### ISSUE THREAD

**Issue by McMartin** [WeAreROLI/JUCE#395]
In commit cf4f12a452611e46d29e4549ce69adac345706b7 ("Replaced our VST2 interface headers with official VST3 SDK"), many files from the VST3 SDK were added to the repository. 

Most of these files are
> [licensed under the terms of the Steinberg VST3 License, or alternatively under the terms of the General Public License (GPL) Version 3](https://github.com/WeAreROLI/JUCE/blob/cf4f12a452611e46d29e4549ce69adac345706b7/modules/juce_audio_processors/format_types/VST3_SDK/LICENSE.txt#L9-L10). 

However, this
> [license applies only to files referencing this license, for other files of the Software Development Kit the respective embedded license text is applicable](https://github.com/WeAreROLI/JUCE/blob/cf4f12a452611e46d29e4549ce69adac345706b7/modules/juce_audio_processors/format_types/VST3_SDK/LICENSE.txt#L5-L7). 

The 3 following files don't reference this license:
- [modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/aeffect.h](https://github.com/WeAreROLI/JUCE/blob/cf4f12a452611e46d29e4549ce69adac345706b7/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/aeffect.h)
- [modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/aeffectx.h](https://github.com/WeAreROLI/JUCE/blob/cf4f12a452611e46d29e4549ce69adac345706b7/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/aeffectx.h)
- [modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/vstfxstore.h](https://github.com/WeAreROLI/JUCE/blob/cf4f12a452611e46d29e4549ce69adac345706b7/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x/vstfxstore.h)

Instead, these 3 files contain the following notice:
```cpp
// LICENSE
// (c) 2018, Steinberg Media Technologies GmbH, All Rights Reserved
//-----------------------------------------------------------------------------
// This Software Development Kit may not be distributed in parts or its entirety  
// without prior written agreement by Steinberg Media Technologies GmbH. 
// This SDK must not be used to re-engineer or manipulate any technology used  
// in any Steinberg or Third-party application or software module, 
// unless permitted by law.
// Neither the name of the Steinberg Media Technologies nor the names of its
// contributors may be used to endorse or promote products derived from this 
// software without specific prior written permission.
```

This means that JUCE containing these 3 files cannot be redistributed, thus is no longer GPLv3.

Maybe ROLI and Steinberg do have a written agreement that allows ROLI to publish these 3 files on https://github.com/WeAreROLI/JUCE, but every single fork of JUCE (there are 533 forks as I write) might infringe the Steinberg license by simply updating their `develop` branch to match the `develop` branch of https://github.com/WeAreROLI/JUCE.

Please remove these 3 files, so I can update my fork of JUCE (https://github.com/McMartin/JUCE) without infringing any license.

**Comment by McMartin** [comment]
I linked to that issue on the JUCE forum: https://forum.juce.com/t/the-future-of-vst2-support-in-juce/28077/25

**Comment by brylie** [comment]
Looking at this issue and the fact that Juce 5 requires developers to agree to a privacy policy allowing data collection from end users, Juce is not very appealing for open source projects. It is a shame, as in videos from even one year ago Juce seemed to be a mature and thriving open source projects. Even the commit history seems to be dwindling significantly over the past year. What is going on with this project? Should we look for alternative frameworks for open source audio development?

**Comment by julianstorer** [comment]
If you remove these files in a commit on your own fork, the material will be gone. 

And what's more, the resulting repo will be exactly the same as it would be if _we_ deleted the files. The only difference would be the name on that commit.

So there's really no benefit to be gained from us removing it ourselves globally. That'd just inconvenience a whole chunk of our userbase for whom these files are really helpful.
