### ISSUE TITLE
Linux Plugin link time optimization fails by default.

### ISSUE THREAD

**Issue by mtytel** [WeAreROLI/JUCE#403]
I'm building a VST plugin for Linux. If I enable link time optimization in Projucer, the generated Makefile fails on the ar command when building the shared library.

By default AR is mapped to the 'ar' command and fails but I can fix this by passing in the 'gcc-ar' wrapper instead. 
`make AR=gcc-ar`

**Comment by tpoole** [comment]
This isn't something we can fix in JUCE - the appropriate `AR` environment variable is determined by the toolchain. In your case you're using  gcc but you could also be using clang or a more exotic one targeting an embedded platform. The existing default of `AR=ar` is probably the most widely used.

The solution is to do as you've done and provide the correct executables when running `make`.
