### ISSUE TITLE
juce_mac_Video.h compiler warning

### ISSUE THREAD

**Issue by m-hilgendorf** [WeAreROLI/JUCE#407]
When compiling with -Wextra on OSX there is a warning in juce_mac_Video.h (omitting file paths for brevity): 

```
In file included from .../JUCE/modules/juce_video/playback/juce_VideoComponent.cpp:31:
.../JUCE/modules/juce_video/playback/../native/juce_mac_Video.h:118:67: warning: missing field 'epoch' initializer [-Wmissing-field-initializers]
                         (CMTimeScale) 100000, kCMTimeFlags_Valid 

```

This can be reproduced by creating a new GUI app in the projucer, adding -Wextra to compiler flags and compiling on OSX High Sierra, edit: I'm using the latest tip from develop

**Comment by ed95** [comment]
Thanks. Fixed in [13a4f51](https://github.com/WeAreROLI/JUCE/commit/13a4f5126f0f5d8ed4354b2555fa6228ff32bde9).
