### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by truongnn** [WeAreROLI/JUCE#410]
We should have this call in the destructor to prevent a memory leak:
`[view release];`

https://github.com/WeAreROLI/JUCE/blob/fe6fa12f551357c2ba5a5cf1ca6041d084c9dee8/modules/juce_opengl/native/juce_OpenGL_osx.h#L68

**Comment by julianstorer** [comment]
Ah - good catch! Thanks, I wonder why we never caught that ourselves in the memory sanitiser...?
