### ISSUE TITLE
Window unclickable / clicks-through with Wayland. (Helm 0.9.0

### ISSUE THREAD

**Issue by vblanton** [WeAreROLI/JUCE#412]
Hello,

I'm not sure if this is a JUCE bug, or a Helm bug, but one suggestion was to take this up here. Here is the original bug report with Helm:
https://github.com/mtytel/helm/issues/160

Symptom / How to reproduce:

Running on Wayland, the Helm window registers MIDI keyboard and plays sound, but all mouse clicks on the window pass right through to whatever is behind it (application or desktop).

Expected Behavior: Clicking interacts with the application window, allows me to choose settings, etc. 

Operating System: Linux. Bug reproducible on Fedora Linux 28 and Ubuntu 18.04.1 with Wayland. Helm 0.9.0.

Architecture: 64bit.

Stack trace: no crash / no trace

No Plugin. Standalone DAW, Helm. ( https://tytel.org/helm/ )

**Comment by tpoole** [comment]
Unfortunately there is no Wayland support in JUCE at the moment.

**Comment by vblanton** [comment]
Please consider supporting wayland. It is the direction that the linux desktop is going to, with a number of distributions already loading it by default. For now, however, it is good to know there is a backup solution.
