### ISSUE TITLE
JSON::toString outputs invalid JSON when the var contains non-finite numbers

### ISSUE THREAD

**Issue by hiddedejong** [WeAreROLI/JUCE#425]
Passing a var containing non-finite numbers result in an invalid JSON string.

Example:
```
// converting a var containing INFINITY to a string

var v(new DynamicObject());
v.getDynamicObject()->setProperty("nan", NAN);
v.getDynamicObject()->setProperty("infinity", INFINITY);
String s = JSON::toString(v);


// output

{
  "nan": nan,
  "infinity": inf
}
```

The JSON spec does not include these non-finite values, and trying to parse `JSON::toString`'s output in any JSON parser fails. (JUCE's `JSON::parse` included.)

A possible solution is to return `null` for non-finite values. Node, Chrome and Safari all do this when using `JSON.stringify`.
```
// in Chrome:

JSON.stringify({ "nan": NaN, "infinity": Infinity });


// output

{
  "nan": null,
  "infinity": null
}
```

**Comment by julianstorer** [comment]
Thanks, a fix for that should appear shortly!
