### ISSUE TITLE
FR: PluginHostType: add recognition of Cakewalk by Bandlab

### ISSUE THREAD

**Issue by yfede** [WeAreROLI/JUCE#429]
After Cakewalk has been acquired by Bandlab, the DAW that was once called SONAR is not officially dubbed "Cakewalk by Bandlab".

`PluginHostType` does not recognize this new incarnation and, in addition to adding support for it, I would recommend to still consider it in the` isSonar()` family, because it looks like it still is 99.9% SONAR, so any condition that required SONAR to be identified, probably is still valid with this new version.

I have added support in my local copy of JUCE this way:

1. Added `CakewalkByBandlab` entry in the `HostType` enum
2. added the following line to the code that detects DAWs on Windows (it still is Windows-only):
`if (hostFilename.equalsIgnoreCase   ("Cakewalk.exe"))      return CakewalkByBandlab;`
3. added `CakewalkByBandlab` among the types for which `isSonar()` returns `true`
4. added the relevant isCakewalkByBandlab() and `case` entry in `getHostDescription()`

**Comment by ed95** [comment]
Added in [a1042a6](https://github.com/WeAreROLI/JUCE/commit/a1042a6e24db7e3bb8f3b6e009b1d0de39207d6d).
