### ISSUE TITLE
SIMDRegister's lessThan and lessThanAreEqual have swapped implementations.

### ISSUE THREAD

**Issue by mtytel** [WeAreROLI/JUCE#432]
lessThan should use greaterThanOrEqual and lessThanOrEqual should use greaterThan, but the implementation has it vice versa.

https://github.com/WeAreROLI/JUCE/blob/04c931ad569da9944aa7ac5f7e471fcfe15c5966/modules/juce_dsp/containers/juce_SIMDRegister.h#L296

    static inline vMaskType JUCE_VECTOR_CALLTYPE lessThan (SIMDRegister a, SIMDRegister b) noexcept { return toMaskType (NativeOps::greaterThan (b.value, a.value)); }
    
    static inline vMaskType JUCE_VECTOR_CALLTYPE lessThanOrEqual (SIMDRegister a, SIMDRegister b) noexcept { return toMaskType (NativeOps::greaterThanOrEqual (b.value, a.value)); }

**Comment by tpoole** [comment]
This is working correctly; we're not *negating* the `greaterThan` and `greaterThanOrEqual` results, we're flipping the arguments instead.
