### ISSUE TITLE
Is juce_VSTInterface.h legal?

### ISSUE THREAD

**Issue by ShigekiKarita** [WeAreROLI/JUCE#433]
https://github.com/WeAreROLI/JUCE/blob/master/modules/juce_audio_processors/format_types/juce_VSTInterface.h

I want to use this header for my VST2 project instead of Steinberg's pluginterface deleted  in the latest VST SDK. So I want to make sure this header is legal because steinberg's header says its SDK may not be distributed. How do you avoid this?

**Comment by tpoole** [comment]
It would be legal for you to *use* `juce_VSTInterface.h`, but not for you to *distribute* it - which includes having that file in a public code repository.

We have a special agreement in place with Steinberg with regards to distributing parts of the VST2 and VST3 SDK (and keeping them in our git history), but in any case that file is being removed in the next JUCE release.

**Comment by ShigekiKarita** [comment]
Thanks. I'm grad to know that. So is it still possible to get this header
from previous releases?

2018年11月5日(月) 16:36、Tom Poole さん（notifications@github.com）のメッセージ:

**Comment by tpoole** [comment]
Yes, it's still possible to get the header. However, in the next release, it will not be compatible with JUCE. We have moved to using the VST2 SDK directly (which is also available in JUCE 5.3.2).

**Comment by ShigekiKarita** [comment]
OK. I will use it anyway. Thanks!
