### ISSUE TITLE
 int64 AudioFormatReader::searchForLevel

### ISSUE THREAD

**Issue by tttthiagoooo** [WeAreROLI/JUCE#434]
I found an error in the searchForLevel function, it is returning -1 for "big" readers.

Because of this cast in lengthInSamples, which is an int64, but the bufferStart is also int64.

...
if (bufferStart >= (int) lengthInSamples)
            break;
...

https://github.com/WeAreROLI/JUCE/blob/d51a44a58ec686b627d38168e301840288674645/modules/juce_audio_formats/format/juce_AudioFormatReader.cpp

**Comment by ed95** [comment]
Thanks for reporting. Fixed in [4b92a04](https://github.com/WeAreROLI/JUCE/commit/4b92a04e27559036e1fed1232e53c38dd0265943).
