### ISSUE TITLE
Default Android project targets very old API

### ISSUE THREAD

**Issue by dturner** [WeAreROLI/JUCE#435]
JUCE 5.4 targets Android API 10 (Gingerbread) as the default API. This API has only a 0.2% market share: https://developer.android.com/about/dashboards/

Since this devices running this API are generally very old (in mobile terms) and quite difficult to get hold of for testing, it's probably worth bumping the default Android version to 16 (Kit Kat) since this would still give 99.5% coverage.

**Comment by lukaszkozakiewicz-roli** [comment]
Good point. In fact we have just bumped the min supported Android version to 16 in this commit on develop branch: https://github.com/WeAreROLI/JUCE/commit/008b7a9ab2960f265c6ca305edfba29859a4548a

**Comment by dturner** [comment]
Sorry, I should've checked that first. Thanks for the quick response! 

I've verified that platform-16 is targeted on the develop branch.
