### ISSUE TITLE
Possible misleading doc comment

### ISSUE THREAD

**Issue by mynameisjohn** [WeAreROLI/JUCE#443]
https://github.com/WeAreROLI/JUCE/blob/e786f9c0aa94cd67376d6863a5cfac1ca6d818c9/modules/juce_core/containers/juce_ListenerList.h#L105

Shouldn't the comment read "Returns true if no listeners are registered"?

**Comment by tpoole** [comment]
Thanks.

Fixed on the `develop` branch.
