### ISSUE TITLE
Slider Textbox formatting broken

### ISSUE THREAD

**Issue by peterStitt** [WeAreROLI/JUCE#450]
When attaching a slider to a parameter using SliderAttachment the formatting of the value in the Slider's text box is incorrect compared to JUCE 5.3.2 - the number of displayed decimal places is inconsistent with the set range of for the parameter.

**Expected behaviour:**
In JUCE 5.3.2, the number of decimal places used for display are based on the step size of the NormalisableRange. For example, when setting up a parameter in the APVTS, using
`NormalisableRange<float> (0.0f, 10.0f, 1.f)`
would display in the slider text box as an integer with a value from 0 to 10.

**Current behaviour:**
The above code in version 5.4.1 now displays with decimal places. For step sizes <1 the number of decimal places changes based on the actual value, rather than the step size.

The cause might be here: https://github.com/WeAreROLI/JUCE/commit/1f63493031e1e42d3986fba722d125466cb55fec#diff-1ec75d23db30b69cffab9854fa6697f4R578
It seems like textFromValueFunction and valueFromTextFunction are always set when in the SliderAttachment, even if set to nullptr when creating the parameter. Previously there was a check so if the parameter's valueToTextFunction was set as nullptr, the slider's valueToTextFunction would also be nullptr. This is no longer the case.

**Comment by ed95** [comment]
Fixed in [57421a9](https://github.com/WeAreROLI/JUCE/commit/57421a90419f69db9218073fc7763829f011e3e6).
