### ISSUE TITLE
Segfault in Demo Runner on Mac OS

### ISSUE THREAD

**Issue by boredstiff** [WeAreROLI/JUCE#458]
1) To reproduce:
     - Install JUCE for Mac from website
     - Open DemoRunner
     - Go to Browse Demos > GUI > ComponentTransformsDemo.h
     - Crash
        - Also crashes on WidgetsDemo.h, OpenGLDemo2D.h
  2) the expected behaviour - Don't crash
  3) the operating system - Darwin 10.14.2 18C54
  4) the architecture (64-bit)
  5) [OS Stack Trace is here](https://github.com/WeAreROLI/JUCE/files/2722806/demo_runner_crash.txt)
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - N/A
  7) which DAW you observed the bug in - N/A

I'm using the installation from the website, not compiling from source. Juce v5.4.1 built on Dec 4 2018

**Comment by ed95** [comment]
This has been fixed on the develop branch.
