### ISSUE TITLE
Initialise AudioDeviceManager return empty String when there's no available devices

### ISSUE THREAD

**Issue by czyjerry** [WeAreROLI/JUCE#462]
the link of the same issue reported on the forum: https://forum.juce.com/t/bug-report-initialise-audiodevicemanager-return-empty-string-when-theres-no-available-devices/31164

Initialise AudioDeviceManager return empty result String when there’s no available audio device.
But it was failed actually. (No way it should succeed in this situation)
But the document said:

> an error message if anything went wrong, or an empty string if it worked ok.

Returning an empty String should mean that the initialisation have succeeded, but in this case it’s not.
So I think this might be a JUCE bug.

The environment can be sth. like the img below:
![2](https://user-images.githubusercontent.com/12249229/50807293-b35db200-1334-11e9-91c4-4e45027aad8b.png)

Thx.

**Comment by ed95** [comment]
Closing this issue as it has been fixed on the develop branch (see forum thread for more details).
