### ISSUE TITLE
OSX Compilation of AU plugin fails if AU Export Prefix includes dash

### ISSUE THREAD

**Issue by Vallant** [WeAreROLI/JUCE#464]
Hello,
maybe a unusual case, but i recently created a plugin project called "juce-test" and wanted to generate a AU plugin. 

Now on compilation on OSX 10.11 using the development tip of JUCE (and a freshly built Projucer) under the project settings the default value of the "Plugin AU Export Prefix" i overrode the default value and put "juce-testAU" (with the dash). 

This however resulted in a compilation error at the end of the `juce_AU_Wrapper.mm` class.

While it is (now) clear that it isn't a good idea for a macro to include dashes, maybe the user should be warned about this in the projucer ;-)

Thanks,
Stephan

**Comment by ed95** [comment]
If you click the info button next to the setting name, you will see this tooltip:

"A prefix for the names of exported entry-point functions that the component exposes - typically this will be a version of your plugin's name that can be **used as part of a C++ token.**"

I think this is clear enough.
