### ISSUE TITLE
Expected Clang 7

### ISSUE THREAD

**Issue by etaylor4848** [WeAreROLI/JUCE#466]
After finally figuring out that when files like windows.h is missing and needing to specify my Windows SDK version, this this error came up when building DemoRunner:
`STL1000: Unexpected compiler version, expected Clang 7 or newer.`

I had downloaded G++ before doing anything in Projucer, seeing that it was a recommended compiler, but now I need Clang?

I downloaded the 7.0.1 version, but I still get the error. I was looking for a spot to specify the file path within Projucer, but couldn't find one. Do I include the file path in my system's environment variables? I did include Cygwin, though, if I'm not mistaken, is not the compiler I need.

Does anyone have any idea what I'm doing wrong?

OS: Windows 10 64-bit

**Comment by ed95** [comment]
You'll need to delete the live-build .dll and re-download it - please see [this post](https://forum.juce.com/t/projucer-5-0-0-memory-leak/22100/12?u=ed95) for details on how to do that.
