### ISSUE TITLE
External Drag and Drop - Windows

### ISSUE THREAD

**Issue by emainier** [WeAreROLI/JUCE#469]
It seems JUCE 5.4 is breaking the drag and drop from plugin to host under certain conditions.

I have the same code running on JUCE 5.3 and I am able to drag and drop MIDI files without issue from my plugin to Samplitude and Mixcraft on Windows 10 - 64bit.

Both DAWs become unresponsive when doing the same operation using JUCE 5.4.1. After the drag, it seems the focus is never given back to the DAW or the plugin. It requires the task manager to kill the software as the UI becomes completely blocked. Other DAW like Ableton, Studio One, Bitwig seem to work normally.

I am using the "startDragging()" method and "shouldDropFilesWhenDraggedExternally()" to handle the drag and drop. Is there something I have missed when migrating to 5.4 ?

Any chance someone can help figuring out what's going on? I would guess it has to do with the drag and drop becoming asynchronous, and I am wondering if it comes from those specific DAWs not handling async drag and drop properly or if it could come from JUCE.

Thanks

**Comment by ed95** [comment]
This should be fixed in [3b16efc](https://github.com/WeAreROLI/JUCE/commit/3b16efce0b9b76eac7762765030e0448ff8de831), please give it a test and let me know.

**Comment by emainier** [comment]
This seems to have fixed it. Thanks.
