### ISSUE TITLE
AudioProcessor::getWrapperTypeDescription - Missing case for wrapperType_Unity

### ISSUE THREAD

**Issue by eliottparis** [WeAreROLI/JUCE#482]
https://github.com/WeAreROLI/JUCE/blob/839ca117463d3f22d856c7f33c52af9eb8f1021b/modules/juce_audio_processors/processors/juce_AudioProcessor.cpp#L1402-L1416

**Comment by ed95** [comment]
Added in [24de5cf](https://github.com/WeAreROLI/JUCE/commit/24de5cf3c2df5c38395fb88b62ef16b99fe9187c) - thank you for reporting.
