### ISSUE TITLE
JUCE 5.4.2 cannot open VS2017 solution when using multiple user modules

### ISSUE THREAD

**Issue by czyjerry** [WeAreROLI/JUCE#486]
I’m using two User Modules paths separated by a semicolon which is set in the “Global Paths”.
And if I checked the “Use global path for this module”(which is the default setting),  the VS2017 solution cannot be opened, and the following error message is displayed:

> error : File E:\my-modules is included into ClCompile and ClInclude item groups. This is not allowed for project items, which can belong to only one item group.

But if I unchecked it, the solution will be opened successfully.

Can you fix this?
Thx!

**Comment by czyjerry** [comment]
Here is the forum thread: https://forum.juce.com/t/juce-5-4-2-cannot-open-vs2017-solution-when-using-user-modules/31775

**Comment by ed95** [comment]
Resolved in [da4c1eaf](https://github.com/WeAreROLI/JUCE-dev/commit/da4c1eaf31cbf2070383eac89221088ec53981f5).
