### ISSUE TITLE
Possible minor error: OpenGLShaderProgram::Uniform::set (GLfloat n1, GLfloat n2, GLfloat n3, float n4) should be 4 GLfloats ?

### ISSUE THREAD

**Issue by ianacaburian** [WeAreROLI/JUCE#487]
As titled.

**Comment by ed95** [comment]
Fixed in [5bdd3ea](https://github.com/WeAreROLI/JUCE/commit/5bdd3ea8c64ef5cf2a22f9d3c55308e2ea4b94db), thanks for reporting.
