### ISSUE TITLE
Build issue with juce_shouldDoubleScaleNativeGLWindow

### ISSUE THREAD

**Issue by otristan** [WeAreROLI/JUCE#491]
in juce_PluginUtilities.cpp juce_shouldDoubleScaleNativeGLWindow should be guarded by
#if JUCE_MODULE_AVAILABLE_juce_opengl && (JucePlugin_Build_VST || JucePlugin_Build_VST3)
otherwise you get a double definition when not building a VST

Thanks !

**Comment by ed95** [comment]
Added in [77db5fd](https://github.com/WeAreROLI/JUCE/commit/77db5fde66d0946103f544e17ebbcc748bf6fb56). Thanks for reporting.
