### ISSUE TITLE
Projucer overwrites existing files without warning when using "Add new CPP & header file"

### ISSUE THREAD

**Issue by B-Raffai** [WeAreROLI/JUCE#498]
Steps to reproduce:
* Create a project in the Projucer (I'm using an audio effect project)
* Click on an "Add new CPP & header file"
* Select PluginEditor.h
* Click OK

After reloading the files in the Projucer, they have become blank with only a comment at the top and a single preprocessor directive.

I just destroyed two of my files this way after accidentally clicking this option instead of the "Add existing files...".
I'm using 64-bit Linux.

**Comment by ed95** [comment]
See PR [511](https://github.com/WeAreROLI/JUCE/pull/511).
