### ISSUE TITLE
ADSR : Setting a param to zero sets rate to -1.

### ISSUE THREAD

**Issue by Normalised** [WeAreROLI/JUCE#502]
https://github.com/WeAreROLI/JUCE/blob/c3a8ea1ab62c99fc79e9625505b57e699daa4c7f/modules/juce_audio_basics/utilities/juce_ADSR.h#L214

If you put a decay time of zero, the decay rate ends up as -1. This means that 1 is being added to the envelope level on every step whilst in the decay state and the envelope level rapidly increases and obviously distorts the audio the envelope is being applied to.

The same is true for the attack release parameters, if you set them to zero the rate is set to -1 and the tests for state transitions will fail.

I suggest either a lower bound above zero for each param or check for zero times so the state can be switched immediately from the relevant section.

**Comment by ed95** [comment]
If you examine the code in the `noteOn()` and `noteOff()` methods,  a rate of -1 is used to indicate that the stage should be skipped and won't ever be added to the envelope value. Can you provide an example of this happening?

**Comment by Normalised** [comment]
Yes, If you set attack to any non-zero value and decay to zero you'll see the problem in envelope value immediately. Attack rate will be correctly set, but decay rate will be -1.

Note On does this : 
`    
if      (attackRate > 0.0f)  currentState = State::attack;
else if (decayRate > 0.0f)   currentState = State::decay;
else currentState = State::sustain;`

Which means the envelope will start in attack state as expected BUT the note on conditions don't apply during the attack -> decay state transition. So you end up in decay state with a decay rate of -1, which does this :

`
        else if (currentState == State::decay)
        {
            envelopeVal -= decayRate;

            if (envelopeVal <= sustainLevel)
            {
                envelopeVal = sustainLevel;
                currentState = State::sustain;
            }
}
`
envelope val immediately increments by 1 on the first step of decay state and will therefore never be below the sustain level and continue incrementing.
