### ISSUE TITLE
CmakeLists.txt incorrectly formatted CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#506]
```
$ projucer --version
JUCE v5.4.3
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
```

Steps to reproduce:

- Add a Cmake build to the Projucer
- Save CMakeLists.txt

Expected behaviour:

- CMakeLists.txt is correctly formatted

Actual behaviour:

- -Wreorder is double quoted as shown below 

`set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-common -Wswitch -Wunused-variable -Wparentheses -Wnon-virtual-dtor -Wshorten-64-to-32 -Wundeclared-selector -Wuninitialized -Wunused-function -Wbool-conversion -Wcomma -Wconstant-conversion -Wempty-body -Wenum-conversion -Winfinite-recursion -Wint-conversion -Wrange-loop-analysis -Wstrict-prototypes -Wmove -Wunreachable-code -Wduplicate-method-match "-Wreorder"")`

This causes make to fail after Cmake has completed.

**Comment by McMartin** [comment]
AFAIK, this was fixed on:
- the `develop` branch: https://github.com/WeAreROLI/JUCE/commit/42301905e29dd4b112c8d2deb52da80bb90253ac
- the `master` branch: https://github.com/WeAreROLI/JUCE/commit/91ed59d117ead48623fad7d7379bf642b7b5aa44
- the website downloads (according to https://forum.juce.com/t/clion-exporter-broken-on-repository/31910/9)

**Comment by jamiebullock** [comment]
Ah OK... it seems you're right. Thanks for the quick reply.

(I did check the git logs for "Cmake" but not for "Clion"!)
