### ISSUE TITLE
Data race in ChangeBroadcaster::sendChangeMessage

### ISSUE THREAD

**Issue by danra** [WeAreROLI/JUCE#513]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code
 - Build the juce fork at https://github.com/Celemony/JUCE_ARA/
 - Build the ARA sample plugin at `JUCE/examples/ARA`
 - Run Logic Pro under thread sanitizer.
 - Insert the AU ARA version in Logic Pro.
 - Open the plug-in GUI.
 - Close the plug-in GUI.
 - Thread sanitizer shows a race between removing the listener in a destructor on the main GUI thread, which changes the size of the listeners, list while at the same time `ChangeBroadcaster::sendChangeMessage()` reads `changeListeners.size()` to decide whether to trigger a change message.

  2) the expected behaviour
No data race.

  3) the operating system
macOS 10.14.3

  4) the architecture (32-bit or 64-bit)
64-bit

  5) a stack trace - if the bug causes a crash
Attached

  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
AU (ARA)

  7) which DAW you observed the bug in - if applicable
Logic Pro X

Make sure you have pulled the latest commits from the `develop` branch of the
JUCE repo
- Even though this reproduction is on a fork of the develop branch, it looks like the relevant code hasn't changed in the JUCE develop branch (commit 9fe83c18bd7228e8e814b8e0a684bdfb86c3122a), and this race can occur in general.

Thanks,
Dan
[ara_gui_close_race.txt](https://github.com/WeAreROLI/JUCE/files/3034275/ara_gui_close_race.txt)

**Comment by sgretscher** [comment]
The problem will always show if the reader hasn't finished reading all samples by the time the listener is removed from the thumb. The traces show that part of the problem may be that there's only a DummyCriticalSection being used?
On a related note, the case of properly closing down the time slice usage if still active upon destruction seem not implemented - if the reader is slow or the file is very long, this may cause problems.

**Comment by ed95** [comment]
Fixed in [4aad74d](https://github.com/WeAreROLI/JUCE/commit/4aad74d842d805d3cc6a9c0f3cfde0f8821f870b) - thanks for reporting!
