### ISSUE TITLE
Projucer generates paths to global modules in CMakeLists for headers

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#516]
I may be doing something wrong here, but with the latest version of JUCE and the Projucer from b396673d, if I select: 

- "Use global path for this module" and 
- "Copy the module into the project folder" 

...for a given JUCE module in my project, the generated CMakeLists.txt file paths are correctly generated to point to modules in the JuceLibraryCode within my project folder. However paths are _also_ generated to the module headers in the global path. For example:

```
"../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp"
"../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.h"
"../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.mm"
"../../../../../../../../../JUCE5/modules/juce_audio_processors/juce_audio_processors.h"
```

This means the project can't be built without the global path being present.

**Comment by ed95** [comment]
This should be fixed in [302e4a6](https://github.com/WeAreROLI/JUCE/commit/302e4a6166a5bef2a92df8ef69547f5a1c4facc0) - thanks for reporting!
