### ISSUE TITLE
Rotary slider does not wrap around on mouse wheel when stopAtEnd is not set

### ISSUE THREAD

**Issue by arikauppi** [WeAreROLI/JUCE#518]
Create a rotary slider with stopAtEnd set to false.
Now mouse drag will wrap around the NormalisableRange but adjusting via mouse wheel stops at range ends.

My expectation would be that both drag and mouse wheel would work similarly.

A fix that works for me for this specific use case can be found at https://github.com/arikauppi/JUCE/commit/32f34a1d37cd31d262dcda0d297eda3a4bc06311

**Comment by tpoole** [comment]
Fixed in https://github.com/WeAreROLI/JUCE/commit/92c30e780d7f6fe3acbb2888b45735544dce80c5.
