### ISSUE TITLE
Mouse wheel does not work for Slider attached to AudioParameterChoice

### ISSUE THREAD

**Issue by arikauppi** [WeAreROLI/JUCE#519]
Context: JUCE_5.4.3, can also be reproduced with modules from develop-branch (Projucer from 5.4.3).
Latest Mojave, Reaper, 64-bit VST3 if it makes a difference (should not).

const juce::StringArray choices = {
	"A",
	"B",
	"C",
	"D",
};
    juce::AudioProcessorValueTreeState &parameters;
    parameters.createAndAddParameter(std::make_unique<AudioParameterChoice>("foo", "foo", choices, 0));
    
    knob = new juce::Slider(juce::Slider::SliderStyle::RotaryVerticalDrag, juce::Slider::TextEntryBoxPosition::TextBoxAbove);
    knob->setSliderStyle(juce::Slider::SliderStyle::RotaryVerticalDrag);
    addAndMakeVisible(knob);

    knobAttachment = new juce::AudioProcessorValueTreeState::SliderAttachment(parameters, "foo", *knob);

In above scenario the mouse wheel does not change the parameter to next/previous value.
My expectation would be that mouse wheel would work also for AudioParameterChoice sliders attached with SliderAttachment. Similar to what mouse drag does.

My ugly workaround (which seems to work for my specific use case) was to set range.interval to 1 in AudioParameterChoice::AudioParameterChoice(). After all, for choices the interval should be 1 instead of 0 (continuous). On the other hand, according to comment in NormalisableRange::interval the interval should not be valid if lambda is provided for snapToLegalValueFunction. However, that does not seem to be the case if AudioParameterChoice is attached to a Slider.

For my ugly workaround, see https://github.com/arikauppi/JUCE/commit/4d1e0ce4f5c58ab9244bc61e3df525d8c69ee3f2

**Comment by tpoole** [comment]
https://github.com/WeAreROLI/JUCE/commit/f77bbcd3fb4fa36d743369daa71db75535d7d672
