### ISSUE TITLE
Source code directory in Clion looks weird

### ISSUE THREAD

**Issue by jiemojiemo** [WeAreROLI/JUCE#520]
source code in Producer:
![image](https://user-images.githubusercontent.com/13779459/56035804-bc0fbb00-5d5d-11e9-9ed1-737e1c1a2302.png)

source code in Clion(where is the cpp header?):
![image](https://user-images.githubusercontent.com/13779459/56035819-cb8f0400-5d5d-11e9-8ff6-7080dad18a9c.png)

**Comment by ed95** [comment]
You'll need to change the project root to be the root folder of your JUCE project (the same level as the .jucer file) which you can do by opening the main menu -> tools -> Cmake -> change project root.
