### ISSUE TITLE
Building with gcc 4.9.2 and -std=c++14 fails due to redundant std::make_unique implementation

### ISSUE THREAD

**Issue by centuryglass** [WeAreROLI/JUCE#524]
In JUCE/modules/juce_core/system/juce_CompilerSupport.h, C++14 support is detected in gcc by checking if __cplusplus >= 201402L, and an alternate implementation of std::make_unique is provided if C++14 is unavailable. In GCC 4.9.2, when compiling with the -std=c++14 flag, __cplusplus is set to 201300, JUCE fails to detect C++14 support, and compilation fails because of the ambiguous extra version of std::make_unique.

**Comment by tpoole** [comment]
Fixed in https://github.com/WeAreROLI/JUCE/commit/5c19eacd0b0069a70e4dab9939708bd05c965160.
