### ISSUE TITLE
MIDI input broken in AudioPluginHost on Linux since f0ea1c00a632a2140a1501752cac075ce46ae079

### ISSUE THREAD

**Issue by KottV** [WeAreROLI/JUCE#538]
Hi,
There is no MIDI in AudioPluginHost on Linux since https://github.com/WeAreROLI/JUCE/commit/f0ea1c00a632a2140a1501752cac075ce46ae079

  1) Build recent AudioPluginHost (develop branch), run it, add instrument or just buildin Sine Wave Synth, configure devices if not, play smth on MIDI controller
No midi events sends to plugin. On-screen piano's keys works

  2) MIDI should work
  3) openSUSE TW, gcc 9.1.1
  4) 64 bit
  5) no any suspicious events in strace
  6) any plugin, buildin affected too
  7) AudioPluginHost

I didn't try to compile any plugins with this branch yet, so cannot tell if this affects them too.

**Comment by ed95** [comment]
Fixed in [b2a4aaa](https://github.com/WeAreROLI/JUCE/commit/b2a4aaa33881bcce0e10117199850d2e2df75ba0). Thanks for reporting!
