### ISSUE TITLE
CoreAudioReader::readSamples() bug

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#541]
There is a bug in [CoreAudioReader::readSamples()](https://github.com/WeAreROLI/JUCE/blob/77e93e35e4057f5ce08d352f56762be271dcd482/modules/juce_audio_formats/codecs/juce_CoreAudioFormat.cpp#L457). The bug is present in develop branch at least of revision 16dd266

The bug stems from the fact that the interface to [ExtAudioFileRead](https://developer.apple.com/documentation/audiotoolbox/1486821-extaudiofileread?language=objc) specifies that for the non-const pointer argument `*ioNumberFrames`, "Fewer frames may be read than were requested". 

However `CoreAudioReader::readSamples()` treats `ExtAudioFileRead()` as if it either returns _exactly the number of frames requested_ or fails. As a consequence `readSamples()` works incorrectly when the number of frames read by `ExtAudioFileRead()` is lower than requested.

This can be seen in the code excerpt below:

```
auto numThisTime = jmin (8192, numSamples);
auto numBytes = sizeof (float) * (size_t) numThisTime;

audioDataBlock.ensureSize (numBytes * numChannels, false);
auto* data = static_cast<float*> (audioDataBlock.getData());

for (int j = (int) numChannels; --j >= 0;)
{
    bufferList->mBuffers[j].mNumberChannels = 1;
    bufferList->mBuffers[j].mDataByteSize = (UInt32) numBytes;
    bufferList->mBuffers[j].mData = data;
    data += numThisTime;
}

auto numFramesToRead = (UInt32) numThisTime;
auto status = ExtAudioFileRead (audioFileRef, &numFramesToRead, bufferList);

/****************************************************************************************************************/
//     BUG
//     numFramesToRead may now be less than numThisTime
/****************************************************************************************************************/

if (status != noErr)
    return false;

for (int i = numDestChannels; --i >= 0;)
{
    auto* dest = destSamples[(i < (int) numChannels ? channelMap[i] : i)];

    if (dest != nullptr)
    {
        if (i < (int) numChannels)

           /****************************************************************************************************************/
           //     BUG!!! 
           //     numBytes is numThisTime * sizeof(float) but should be numFramesToRead * sizeof(float) 
           /****************************************************************************************************************/

            memcpy (dest + startOffsetInDestBuffer, bufferList->mBuffers[i].mData, numBytes); 
        else
            zeromem (dest + startOffsetInDestBuffer, numBytes);
    }
}
```

If needed I can provide a simple JUCE project with an audio file that produces erroneous audio output as a result of the above.

**Comment by ed95** [comment]
Thanks for the detailed report! This should be fixed in [869a9fd](https://github.com/WeAreROLI/JUCE/commit/869a9fd9944d4d87246567451ea49cf65eb2b6f9).

**Comment by jamiebullock** [comment]
Hi @ed95, I've just got around to testing this, sorry it's taken so long.

Unfortunately, not only does this not fix the issue, it introduces a new problem.

With the new code if `numFramesToRead` set by `ExtAudioFileRead` is zero the program will go into an infinite loop. This is because `numThisTime` gets set to zero and accordingly `numSamples > 0` always evaluates true.

The fix I have been using is as follows:

```
for (int i = numDestChannels; --i >= 0;)
{
    auto* dest = destSamples[(i < (int) numChannels ? channelMap[i] : i)];

    if (dest != nullptr)
    {
        if (i < (int) numChannels)
            memcpy (dest + startOffsetInDestBuffer, bufferList->mBuffers[i].mData, sizeof (float) * (size_t)numFramesToRead);
        else
            zeromem (dest + startOffsetInDestBuffer, numBytes);
    }
}

if (numFramesToRead == 0) // EOF reached
    break;

startOffsetInDestBuffer += numFramesToRead;
numSamples -= numFramesToRead;
lastReadPosition += numFramesToRead;
```

**Comment by ed95** [comment]
Can we not just add the

```
if (numFramesToRead == 0)
    break;
```

lines to l.496 (after the `status` check)? If it's 0 then no data will be being copied in the channels loop anyway. 

In my tests, the commit above fixed the issue when `ExtAudioFileRead()` sets `numFramesToRead` to fewer samples than expected but perhaps something else is happening in your case. Can you send over the project that you are using?

**Comment by jamiebullock** [comment]
> Can we not just add the
> ```
> if (numFramesToRead == 0)
>     break;
> ```

Yup, assuming we keep 869a9fd, I think that is the best approach. (I posted my code as an illustration, but it was written before your initial fix).

> In my tests, the commit above fixed the issue when ExtAudioFileRead() sets numFramesToRead to fewer samples than expected but perhaps something else is happening in your case.

Well, the docs for `ExtAudioFileRead` state:

```
@param		ioNumberFrames
					On entry, ioNumberFrames is the number of frames to be read from the file.
					On exit, it is the number of frames actually read. A number of factors may
					cause a fewer number of frames to be read, including the supplied buffers
					not being large enough, and internal optimizations. If 0 frames are
					returned, however, this indicates that end-of-file was reached.
```

So regardless of what the calling code is doing you need to account for the case of `ioNumberFrames == 0`.


> Can you send over the project that you are using?

Unfortunately not, for IP reasons. However, I can put together a small test harness with a few example MP3s that demonstrate the problem if that helps?

**Comment by ed95** [comment]
OK, I'll get that added. 

I'm not sure why my previous fix isn't working in your case though, if we get fewer samples than requested then it should correctly slice the read operation and produce the correct output, and did so in my tests, so I'd be curious to see an example audio file that produces the problem with the current code. Thanks!

**Comment by jamiebullock** [comment]
Hey @ed95.

Here's a link to a project that demonstrates the problem: [TestMP3.zip](https://www.dropbox.com/s/9qq9g0clenh5vnb/TestMP3.zip?dl=0)

There are two files in `Builds/MacOSX/build/Debug` that exhibit the symptoms. If you're on Windows, you'll need to move them to the relevant build path.

We're working with a database of over 250k samples and I was able to find these in 2 out of 4 randomly ordered ones that I tried, so it seems pretty easy to find samples that cause the issue.

AFAICT there's nothing sinister going on, it is just a [facet of MP3](http://lame.sourceforge.net/tech-FAQ.txt) that the last frame can be padded with zeroes. It seems like what is happening is that `readSamples()` is asking `ExtAudioFileRead()` to read those extra 1152 samples and `ExtAudioFileRead()` is refusing to do it.

However, if you have any additional insight / explanation I'd be grateful to hear it! Cheers.

**Comment by ed95** [comment]
Thanks for the sample project! But I'm not seeing any difference in output between the fix that I pushed originally and your fix - they're both reading samples from the test MP3 correctly. Are you sure that the fix isn't working for you?

**Comment by jamiebullock** [comment]
Yup that fix causes the program to hang in infinite loop. I just double-checked by doing a fresh clone of JUCE master with my test app.

If I add the lines 

```
if (numFramesToRead == 0)
    break;
```

As suggested above the problem goes away.

Are sure that the samples are being read correctly when my test program runs? I just realised the program contains a bug and in fact if the samples are read correctly the program crashes when the `AudioFormatManager` attempts to delete the `FileInputStream`. So if it "worked" for you I would've expected that behaviour.

I've now created a repo [here](https://github.com/jamiebullock/TestMP3) with JUCE 5.4.4 included and the test program.

If it works I would expect the following output:

```
JUCE v5.4.4
Program ended with exit code: 0
```

Otherwise it just hangs with:
```
JUCE v5.4.4
```

If it still works for you without the additional check for `numFramesToRead == 0` one possible explanation is that the behaviour of `ExtAudioFileRead()` has changed. I'm on OS X 10.14.6, Xcode 10.3

**Comment by ed95** [comment]
I added the EOF check to develop yesterday in [a522312](https://github.com/WeAreROLI/JUCE/commit/a522312b4742e963d3b0286c52cb8b97450bf143) and was testing against that so it wasn't hanging. I meant the output of reading the file as in your post above you said "Unfortunately, not only does this not fix the issue, it introduces a new problem", but I think it has fixed the original issue. Sorry for the confusion.

**Comment by jamiebullock** [comment]
Aha, yes... we were talking about different commits. I can confirm a522312 fixes the issue in its entirety.

**Comment by ed95** [comment]
Great, I'll get that cherry-picked onto the master branch too then. Happy for me to close this issue?

**Comment by jamiebullock** [comment]
Absolutely. Thanks for taking time to resolve.
