### ISSUE TITLE
Projucer trying to add vst3 path trigger assertion in ValueTreeState

### ISSUE THREAD

**Issue by flyingrub** [WeAreROLI/JUCE#561]
1) Open Projucer
  2) Try to set VST3 SDK path
  3) This happens :
```
Builds/LinuxMakefile/build ➜ ./Projucer 
JUCE v5.4.3

**********************************************************
Projucer 5.4.3  ---  Build date: Jul 24 2019
Log started: 25 Jul 2019 1:08:52pm

Linux
CPU: 3620MHz  Cores: 8  15890MB
Loading project: /home/fly/workspace/Redux/Redux.jucer
JUCE Assertion failure in juce_ValueTree.cpp:766
JUCE Assertion failure in juce_ValueTree.cpp:767
```

Operating system : tested on Windows 10 and Arch Linux

**Comment by ed95** [comment]
Did you build the Projucer from the latest develop branch? Does the folder you're trying to set the path to exist? Does this happen if you load one of the JUCE example projects in the Projucer (e.g. the AudioPluginHost)?

**Comment by flyingrub** [comment]
```Projucer/Builds/LinuxMakefile on  develop [!] ➜ ./build/Projucer  
JUCE v5.4.3

**********************************************************
Projucer 5.4.3  ---  Build date: Jul 25 2019
Log started: 25 Jul 2019 2:47:42pm

Linux
CPU: 3609MHz  Cores: 8  15890MB
Loading project: /home/fly/workspace/Redux/Redux.jucer
JUCE v5.4.3

(Projucer:3840): Gtk-WARNING **: 14:47:43.361: GtkPlug only works under X11```
When running projucer compiled from develop on arch linux.

**Comment by ed95** [comment]
Are you setting the VST3 path via the global paths menu or the individual exporter options? I've tried both and am unable to reproduce this on macOS or Linux using the latest develop branch

**Comment by flyingrub** [comment]
I am trying to set this path : 
![image](https://user-images.githubusercontent.com/3988628/62115647-0a1edf00-b2b9-11e9-8192-987dc8a638db.png)

Here is a screenshot of the stacktrace and the assertion error :
![image](https://user-images.githubusercontent.com/3988628/62115564-ebb8e380-b2b8-11e9-9cc0-8d9de4f04096.png)

And here is a link to the project : https://github.com/flyingrub/Redux

**Comment by ed95** [comment]
OK, I see. The property doesn't exist because there shouldn't be an option for setting the VST3 SDK path on Linux as hosting and building VST3s isn't currently supported there. I've pushed [7a7ea0a](https://github.com/WeAreROLI/JUCE/commit/7a7ea0a47125f7cb3fad919fddaf42cf42c110b3) which should sort this out.
