### ISSUE TITLE
note.getFrequencyInHertz calculation mistake

### ISSUE THREAD

**Issue by jtragtenberg** [WeAreROLI/JUCE#562]
I was reading the code around the calculation to get a MPE note frequency in Hertz and on line 71 of the file juce_MPENote.cpp

https://github.com/WeAreROLI/JUCE/blob/master/modules/juce_audio_basics/mpe/juce_MPENote.cpp

there is the expression: 
double MPENote::getFrequencyInHertz (double frequencyOfA) const noexcept
{
    auto pitchInSemitones = double (initialNote) + totalPitchbendInSemitones;
    return frequencyOfA * std::pow (2.0, (pitchInSemitones - 69.0) / 12.0);
}

isn't that 69.0 a typo? This is lowering the tuning of the instrument by 9 semitones every time.
It should be 60.0, which is the MIDI semitone representation of the central A.

**Comment by FigBug** [comment]
60 is middle C. 69 is A440.
