### ISSUE TITLE
AudioPluginHost eates 100% CPU on Linux

### ISSUE THREAD

**Issue by KottV** [WeAreROLI/JUCE#565]
with latest build AudioPluginHost process stays at top with 100% cpu time

perf top --sort comm,dso
gives next output:

    34,33% AudioPluginHost [kernel] ◆
    14,45% AudioPluginHost libpthread-2.29.so ▒
    5,98% AudioPluginHost libX11.so.6.3.0 ▒
    4,28% AudioPluginHost libxcb.so.1.1.0 ▒
    2,98% AudioPluginHost libc-2.29.so ▒
    1,86% AudioPluginHost AudioPluginHost

with some advises I can try investigate it deeply

**Comment by ed95** [comment]
Thank you for reporting. I've pushed a fix in [012c7d0](https://github.com/WeAreROLI/JUCE/commit/012c7d00d24ff983c135444da1c21f54eef9b48f) which should address this. Can you confirm that it fixes the issue for you?

**Comment by KottV** [comment]
Yes, now cpu consumption is normal.
Thnx!
