### ISSUE TITLE
[Feature request] Projucer: "Add new folder"

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#566]
If I want to create a new folder in the source tree of my Projucer project and have that folder mapped to a Projucer group, that workflow is currently quite painful:

- Projucer: Find a file
- Projucer: Right click -> Reveal in Finder
- Finder: Create Folder in filesystem
- Projucer: Right click -> Add Existing files... -> select folder

It would be really useful if a new item could be added to the right-click context menu "Add new folder", which creates a folder at the relevant point in the hierarchy and maps it to a Projucer group.

**Comment by ed95** [comment]
How would this differ to the "Add New Group" menu option in the file tree?

**Comment by jamiebullock** [comment]
Sorry @ed95 ... GitHub submitted the issue prematurely when I hit enter after writing the title. Hopefully this is clearer now?

**Comment by ed95** [comment]
I guess the problem here is that the Projucer source tree and the actual files on disk don't correspond one-to-one, so you can have source files from multiple locations on disk in the tree and the tree doesn't have to represent an existing folder structure. So what would happen if you created a folder in the Projucer source tree using this option? Where would the folder be added to on disk?

**Comment by jamiebullock** [comment]
Hmm... good point. Tricky! I guess this is why Xcode distinguishes groups and folders. 

My assumption here was that groups do map onto a folder tree with corresponding structure and naming, which is how I think a lot of people work (good practice?), although as you say, Projucer doesn't enforce this.

Could it perhaps use the same logic as the "Add new CPP File..." family? They seem to open Finder in the expected place, i.e. if I have a group "Foo" that maps to a folder called "Foo" it opens in that folder, otherwise it opens in the parent of the group. "Add new folder..." could follow the same pattern, but add a group rather than a file in the Projucer.

**Comment by ed95** [comment]
For your use case where you are directly mapping directories and groups it makes sense, but I think that could be quite confusing in general as group != folder. Adding a file via the "Add new.." option makes sense as the file has to exist somewhere on disk before it can be added to a project, but source groups can (and often do) exist only in the source tree.

**Comment by jamiebullock** [comment]
OK fair enough. Happy to close.

I've also now figured out that my workflow can shorten to:

- Projucer: Right click -> Add Existing files... -> **create** folder
- Finder window: Click open

Which isn't too bad.

Thanks for taking time to discuss this.
