### ISSUE TITLE
Viewport incorrectly hides its scroll-bar if its Component is AffineTransformed

### ISSUE THREAD

**Issue by LGoodacre** [WeAreROLI/JUCE#573]
If a Viewport's contained Component has smaller bounds than the Viewport but has been AffineTransformed to be bigger than it, the scroll-bars will annoyingly disappear when you scroll them to the zero position. Try the following example and see.

```
class MainContentComponent  : public Component
{
    Base comp;
    Viewport view;

public:
    MainContentComponent() : comp(Colours::wheat)
    {
        addAndMakeVisible(view);

        comp.setBounds(0, 0, 300, 300);  // smaller than the Viewport...
        comp.setTransform(AffineTransform::scale(2.0f));  // ...but scaled bigger.

        view.setBounds(Rectangle<int>(50, 50, 400, 400));
        view.setViewedComponent(&comp, false);
        view.setScrollBarsShown(true, true);

        view.setViewPosition(200, 200);
        setBounds(0, 0, 500, 500);
    }
}
```
I have traced this bug back to lines 358 and 359 of juce_Viewport.cpp:

```
            hBarVisible = canShowHBar && (hBarVisible || contentComp->getX() < 0 || contentComp->getRight() > contentArea.getWidth());
            vBarVisible = canShowVBar && (vBarVisible || contentComp->getY() < 0 || contentComp->getBottom() > contentArea.getHeight());
```

`contentComp->getRight()` and `getBottom()` don't take into account the AffineTransformation, so `hBarVisible` and `vBarVisible` is set to false.

**Comment by ed95** [comment]
The `Viewport` class doesn't deal with transformed views as the geometry can get really complicated when transforms are involved. You should put your transformed component inside of a non-transformed container which changes its size when the child is transformed and use that as the view.

**Comment by LGoodacre** [comment]
Fair enough, that makes sense.

If you'll allow me to make a suggestion, you might consider putting a small disclaimer in the AffineTransform documentation, explaining that some of the standard methods in Component and Viewport are incompatible with Affine Transformations. It is quite confusing for new users what apply Affine Transformations and find that they create a lot of unexpected behavior with the Component and Viewport classes. A small note like this could shave some time off the JUCE learning curve.
