### ISSUE TITLE
Classes and Functions Which Are Used in Other Modules Should have Public Visibility

### ISSUE THREAD

**Issue by mfisher31** [WeAreROLI/JUCE#577]
This makes it possible to compile each module separately as a shared library.  I'm working on a project which builds JUCE as shared libraries + creates necessary pkg-config files for system-wide installation.  If I enable `-fvisibility=hidden` in CXXFLAGS, the whole thing breaks down.

See: https://github.com/kushview/libjuce <-- complete build of JUCE using the Waf meta build system.   The master branch doesn't enable hidden visibility, and compiles just fine.  The `visibility` branch fails terribly using stock JUCE when hidden is turned on.

Example of multilibs compiling with hidden visibility:
- https://github.com/kushview/libjuce/tree/visibility
- https://github.com/kushview/JUCE/tree/multilibs

**Comment by julianstorer** [comment]
It has never been a design goal for juce to allow modules to be individually pre-compiled, even as static libs, and we only reluctantly support building a single DLL containing a set of modules.

TBH it sounds to me like a versioning/installation nightmare to have a folder full of DLLs for every platform, I honestly can't imagine any good use-case for doing it like that!

If we were to merge these changes and people started using the library in that way then we'd be obliged to maintain ongoing support for them, which would involve extra CI and work for the team, so I don't think we want to go down that road.

**Comment by julianstorer** [comment]
Thanks - yeah, this kind of thing is just not a good fit with the way juce is structured. Hoping that once C++20 modules are standard, that might help ease the packaging/deployment stuff a bit!
