### ISSUE TITLE
Crashes on LinuxVST

### ISSUE THREAD

**Issue by KottV** [WeAreROLI/JUCE#579]
With 5.4.4 release I found that JUCE apps segfaults on some Linux VSTs that worked normally before, 5.4.3 for example

  1) run AudioPlugin Host, load lv2vst plugin https://github.com/x42/lv2vst , double click on plugin to open GUI
  2) plugin should be opened
  3) Linux openSUSE TW gcc 9.1.1
  4) 64 bit
  5) Thread 1 "AudioPluginHost" received signal SIGSEGV, Segmentation fault.
0x00000000004fdd1d in juce::VSTPluginWindow::VSTPluginWindow (this=0xb43ed0, plug=...) at ../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:2799
2799            setSize (rect->right - rect->left, rect->bottom - rect->top);

  6) VST
  7) AudioPluginHost and Tracktion Waveform 10.2.5 beta

I know that plugin is experimental but it worked like charm in previous verions

**Comment by ed95** [comment]
I can't get lv2vst to be recognised by any hosts on Ubuntu 18.04. Are you seeing this crash with any other VST plug-ins that I can test with?

**Comment by KottV** [comment]
(un)fortunately no, I tested bunch of my vsts's and most of them loads most normal, except some random crashes, but not reproducible
Of course it is not blocking bug, but lv2vst works with the JUCE 5.4.3 and 5.3.2, and other hosts
if You mind - I can help with build and run it on Ubuntu 18.04

**Comment by ed95** [comment]
Can you change line 2797 of `juce_VSTPluginFormat.cpp` to the following and see if it still crashes?

```
Vst2::ERect* rect = nullptr;
dispatch (Vst2::effEditGetRect, 0, 0, &rect, 0);
        
if (rect != nullptr)
    setSize (rect->right - rect->left, rect->bottom - rect->top);
else
    setSize (1, 1);
```

**Comment by KottV** [comment]
Yes! It helped.

**Comment by ed95** [comment]
OK, I've pushed this to develop in [7cb771a](https://github.com/WeAreROLI/JUCE/commit/7cb771a64264d0f863f18e1bb0bfabd7c67113f0).
