### ISSUE TITLE
Projucer 5.4.4 Ubuntu 18.04: glibc v 2.29 required 

### ISSUE THREAD

**Issue by yeeking** [WeAreROLI/JUCE#580]
Hello, 

Linux version: Ubuntu 18.04.3 LTS

Just downloaded JUCE 5.4.4 and when I run it, I see this:

```
./Projucer 
./Projucer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Projucer)
```
I am up to date as of today and have version 2.27

```
apt-cache policy libc6
Installed: 2.27-3ubuntu1
```
5.4.3 was working fine.

It would be great if 5.4.4 was compatible with the current Ubuntu LTS version. 

cheers

Matthew

**Comment by tpoole** [comment]
Thank you for reporting. This is now fixed in the website downloads.
