### ISSUE TITLE
JUCE 5.4.4 Linux UI widget scaling: too big widgets

### ISSUE THREAD

**Issue by atsushieno** [WeAreROLI/JUCE#581]
This is new issue in JUCE 5.4.4 on Linux. Previously there was no problem on widget scaling, but now everything in JUCE widgets are too big. This screen shot would tell:

![image](https://user-images.githubusercontent.com/53929/64394518-89aa8580-d091-11e9-9594-9f30814a21c4.png)

There are Firefox, Nautilus (GNOME), QTractor (Qt), Projucer and Waveform 10 beta (JUCE). Only Projucer and Waveform 10 are looking weird.

You can still scale those JUCE windows, but things like file menu items are not.

Confirmed rev: 4126dc7.

I'm on Ubuntu 19.04 GNOME + Ubuntu (non-Wayland, but also happens on Wayland). Also the display settings would be related (it is 4k display, scaling 2x):

![image](https://user-images.githubusercontent.com/53929/64394575-c8404000-d091-11e9-8ead-37b2b409212f.png)

**Comment by atsushieno** [comment]
Now I'm running Projucer on different display scaling, which is 2048x1152 with "100%" scale. W9 and W10 look good but Projucer looks horrible. I cant simply configure global paths on its UI:

![image](https://user-images.githubusercontent.com/53929/66048284-37f7fc80-e564-11e9-8b3d-41b202615e9e.png)

**Comment by ed95** [comment]
I'm not seeing this issue on Ubuntu 19.04. To see if this might be a config issue, can you post the output of the following commands:

`gsettings get org.gnome.desktop.interface scaling-factor`

and:

`xrandr`

**Comment by atsushieno** [comment]
So far this is the environment at my last comment: https://github.com/WeAreROLI/JUCE/issues/581#issuecomment-537494364

```
~$ gsettings get org.gnome.desktop.interface scaling-factor
uint32 0
~$ xrandr
Screen 0: minimum 320 x 200, current 2048 x 1152, maximum 8192 x 8192
XWAYLAND0 connected 2048x1152+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
   2048x1152     59.83*+
```

**Comment by ed95** [comment]
Does setting `scaling-factor` to 1 by doing `gsettings set org.gnome.desktop.interface scaling-factor 1` fix the issue?

**Comment by atsushieno** [comment]
ahh it did fix all those relevant stuff (Projucer, AudioPluginHost, Waveform10, as well as Collective launched from W10). It feels weird that only JUCE based apps are affected, but that's it anyways. Not sure if you guys have anything left to fix but I'm happy to close this issue. Thanks!

**Comment by ed95** [comment]
Thanks for testing. We've had other reports of similar issues which have been fixed by this so I think that we should treat a `scaling-factor` of 0 in the GNOME settings file as 1 (it seems this is what other apps are doing too).

**Comment by ed95** [comment]
This has now been added in [be134d9](https://github.com/WeAreROLI/JUCE/commit/be134d9185252c65534094903a2c9b99d1bd826d). I'm going to close this issue but feel free to reopen if you run into any more issues.
