### ISSUE TITLE
BUG (WITH FIX): parsePathString does not correctly parse elliptical arc flags

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#584]
@julianstorer 

The following path is not parsed correctly
```M0 0 a4 4 0 01-2 .5 3 3 0 1-2-.7z```
the result should look like this (chrome, quicklook):
![image](https://user-images.githubusercontent.com/1545101/64480520-aba72380-d1c9-11e9-887a-9867cd62adf3.png)

but JUCE shows it like this (please ignore the inverted colours, it's about the shape):
![image](https://user-images.githubusercontent.com/1545101/64480522-b5c92200-d1c9-11e9-98af-de189e51a340.png)

The reason is, that per the [SVG Path BNF](https://www.w3.org/TR/SVG11/paths.html#PathDataBNF) the large-arg-flag and large_arc_flag sweep_flag are "flags" not numbers. So '01' should be interpreted like '0 1' in this case. And indeed: Changing the path to: ```M1 6 a4 4 0 0 1-2 .5 3 3 0 1-2-.7z``` yields the correct result.

the offending code starts here: [juce_SVGParser.cpp:373](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_gui_basics/drawables/juce_SVGParser.cpp#L373). A "flag" needs to be parsed as a single character of either "0" or "1".

**Comment by beschulz** [comment]
changing the code to

```
            case 'a':
                if (parseCoordsOrSkip (d, p1, false))
                {
                    String num;

                    if (parseNextNumber (d, num, false))
                    {
                        const float angle = degreesToRadians (num.getFloatValue());

                        if (*d == '0' || *d == '1')
                        {
                            const bool largeArc = *(d++) != '0';

                            if (*d == '0' || *d == '1')
                            {
                                const bool sweep = *(d++) != '0';

                                if (parseCoordsOrSkip (d, p2, false))

```

appears to be working for my case

**Comment by ed95** [comment]
Thanks! I've added this (and #586) in [d498575](https://github.com/WeAreROLI/JUCE/commit/d49857597639b1df8b07cd59b3d823c966b3882b).
