### ISSUE TITLE
(WITH FIX!) URL::launchInDefaultBrowser() opens wrongly escaped URL on macOS when the URL has parameters

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#585]
@julianstorer (git praise showed you wrote this)

I'm on 5.4.4 master - macOS Mojave, Xcode 10 - using the 10.14 SDK.

When I call:

    URL("https://forum.juce.com/").withParameter("q", "launchInDefaultBrowser").launchInDefaultBrowser();

My browser opens

    https://forum.juce.com/%3Fq=launchInDefaultBrowser

not

    https://forum.juce.com/?q=launchInDefaultBrowser

So currently it's not possible to properly open URLs in the browser that have GET-parameters.

I'm pretty sure this used to work. I'm not sure if this is because of the JUCE 5.4.4 update or because Xcode 10 is using the 10.14 SDK. My WILD GUESS, that in the 10.14 SDK [workspace openFile: juceStringToNS (fileName)] returns true if fileName is an URL, while prior it returned false.

**Comment by beschulz** [comment]
- This does also happen in 5.4.3
- This does not happen in a command line app
- This only happens when "Use App Sandbox" is enabled in the XCode exporter

**Comment by beschulz** [comment]
turns out, my WILD GUESS was sort of right. [workspace openFile: juceStringToNS (fileName)] succeeds for https URLs when sandboxing is enabled, but fails when sandboxing is disabled.

One could work around this issue by checking if the URL starts with "http://" or "https://" - but I think mailto URLs might also be affected.

**Workaround:**

```
if (parameters.isEmpty())
{
    // NB: this check is necessary because "[workspace openFile]" when trying to open a URL and sandboxing is
    // disabled but succeeds when sandboxig is enabled.
    const auto looksLikeURL = fileName.startsWith("http://") || fileName.startsWith("https://") || fileName.startsWith("mailto:");
    // NB: the length check here is because of strange failures involving long filenames,
    // probably due to filesystem name length limitations..
    return (fileName.length() < 1024 && !looksLikeURL && [workspace openFile: juceStringToNS (fileName)])
            || [workspace openURL: filenameAsURL];
}
```

**Comment by kevin--** [comment]
so just to be clear, your original example would succeed if your app is sandboxed?

**Comment by beschulz** [comment]
No, https://forum.juce.com/%3Fq=launchInDefaultBrowser is opened when the app is sandboxed.

**Comment by ed95** [comment]
Is this still an issue? With your example code, https://forum.juce.com/?q=launchInDefaultBrowser is opened when testing with Xcode 10/10.14 SDK and Xcode 11/10.15 SDK (both with "Use App Sandbox" enabled and disabled).

**Comment by beschulz** [comment]
@ed95 : thanks for looking into this! Yes - still happens. I'm on 5.4.5. It's an Audio Plug-In project and I'm running the standalone build. Here are a few more settings that might be relevant:

![image](https://user-images.githubusercontent.com/1545101/67284700-63706600-f4d6-11e9-8675-26ff0a6d1e7c.png)
![image](https://user-images.githubusercontent.com/1545101/67284741-78e59000-f4d6-11e9-862b-e5b24b3a1fd8.png)

**Comment by beschulz** [comment]
@ed95 

Additional Info: You need to set a code signing identity! Attached is a reproduction project - but you need to update the code signing identity to yours.

[URLBug.zip](https://github.com/WeAreROLI/JUCE/files/3755561/URLBug.zip)

Cheers,
Ben

**Comment by ed95** [comment]
I think we're actually OK to just remove the call to `NSWorkspace openFile:` as `openURL` will handle both local files and URLs, `openFile` also seems to have been deprecated in favour of `openURL` since 10.15 anyway. I can't see any issue when opening both local files and URLs after this change so I've pushed it in [1b001e7](https://github.com/WeAreROLI/JUCE/commit/1b001e7a7610ab3ffce3757505fa5f73c3f53ceb). Feel free to re-open this issue if you have any problems.
