### ISSUE TITLE
BUG (with fix*!): SVG "tspans" not parsed at all

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#586]
I have the following SVG:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="81px" height="12px" viewBox="0 0 81 12" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-family="Helvetica" font-size="14" font-weight="normal" letter-spacing="-0.400000006">
        <text id="HELLO-JUCE" fill="#FF00FF">
            <tspan x="-1" y="11">HELLO JUCE</tspan>
        </text>
    </g>
</svg>
```

Unfortunately the DrawableText is never created. The reason appears to be that the text is inside a "tspan".

The bug is parseText() in [juce_SVGParser.cpp:1067](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_gui_basics/drawables/juce_SVGParser.cpp#L1067):

```
Drawable* parseText (const XmlPath& xml, bool shouldParseTransform,
                         AffineTransform* additonalTransform = nullptr) const
{
    ...
    if (! xml->hasTagName ("text")) // (1)
            return nullptr;
    ...
    else if (e->hasTagNameIgnoringNamespace ("tspan")) // (2)
    {
        dc->addAndMakeVisible (parseText (xml.getChild (e), true));
    }
   ...
}
```
In ```(2)``` we recurse if we encounter a "tspan" tag, but in ```(2)``` we abort if the passed tag is NOT "tspan". Changing the early-out to ```if (! xml->hasTagName ("text") && ! xml->hasTagName("tspan"))``` makes the texts re-appear.

**Comment by ed95** [comment]
Thanks! I've added this (and #584) in [d498575](https://github.com/WeAreROLI/JUCE/commit/d49857597639b1df8b07cd59b3d823c966b3882b).
