### ISSUE TITLE
BUG (WITH FIX): ComponentAnimator::fadeOut() blurry when component is scaled up via transform

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#588]
**Reproduction:**
create a component that has some detail and set it's transform so that it is sclaed up 10x or (to exaggerate the problem. then fade out the component via ComponentAnimator::fadeOut() with a long fade duration (again, to exaggerate the problem).

**Observation:**
The fading component is very blurry.

**Expected:**
the fading component is NOT blurry.

**Discussion:**
When fading out component via ComponentAnimator::fadeOut() the useProxyComponent parameter is set to true and the original component is hidden. The ProxyComponent then creates a component snapshot already respecting the display scale - but not the scaling caused by transforms.

**Workaround:**
Use the following to fade out components:
```Desktop::getInstance().getAnimator().animateComponent (component, component->getBounds(), 0.0f, fadeDuration, false, 1.0, 1.0);```

this does not use the proxy component and therefore does not expose the scaling issue. The difference is, that the component ```isVisible()``` will still be true during the fade.

**Fix:**
Create the component snapshot of the proxy component respecting display scale and transform scale:

```image = c.createComponentSnapshot (c.getLocalBounds(), false, scale * Component::getApproximateScaleFactorForComponent(&c));```

**Comment by ed95** [comment]
Thanks! I've added this in [1237b8c](https://github.com/WeAreROLI/JUCE/commit/1237b8c831c0e8018d0cf5f8dac5af687ae52c84).
