### ISSUE TITLE
Projucer: not possible to "not sign" binaries with Xcode 11

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#597]
Steps to reproduce:

- Set the Code-Signing Identity field for an Xcode project in Projucer to "" (i.e. nothing)
- Save and load Xcode project

Expected behaviour:

- The Code Signing Identity is set to "" in Xcode

Actual behaviour:

- The Code Signing Identity is set to "Sign to Run Locally"

The reason for this behaviour is that if no Code Signing Identity is set in Projucer, it does not populate the `CODE_SIGN_IDENTITY `field in the Xcode pbxproj file. This causes Xcode to use its default setting, which is "Sign to Run Locally". What Projucer should actually do is explitly set the field to an empty string:

`CODE_SIGN_IDENTITY = "";`

The problem occurs with Xcode 11 and the latest Projucer code from Develop branch (commit 78fd7a736412171d3df13806a3de4c3c2f5a5ca5)

**Comment by ed95** [comment]
Fixed in [246ab9f](https://github.com/WeAreROLI/JUCE/commit/246ab9f129d215e269e79621905f8c15f70d5883).
