### ISSUE TITLE
Projucer: setting "C++ language standard" to C++17 sets vsproj to stdcpplatest

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#608]
Projucer version 5.4.4

Steps to reproduce:

- Create a project in Projucer
- Set "C++ language standard" to C++17
- Save the project 

Expected behaviour:

- The Visual Studio project has the language standard set to C++17 (/std::c++17)

Actual behaviour:

- The Visual Studio project has the language standard set to "latest" (/std::latest)

**Comment by ed95** [comment]
This has been fixed on the `develop` branch in [e7273fa](https://github.com/WeAreROLI/JUCE/commit/e7273fa0a11c9e0158c63e488e98a1e761cff608).
