### ISSUE TITLE
VST3 scanning can return empty PluginDescriptions after error

### ISSUE THREAD

**Issue by seb-nektar** [WeAreROLI/JUCE#617]
We encountered that problem when trying to scan `Groove Agent SE 5` on OSX but probably other non-conformant plugins can show the same behaviour.

**Problem Description**

[`DescriptionFactory::findDescriptionsAndPerform()`](https://github.com/WeAreROLI/JUCE/blob/724ae27c71ef809b836df06713cf9e50bc14162b/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L703) called by [`getAllDescriptionsForFile()`](https://github.com/WeAreROLI/JUCE/blob/724ae27c71ef809b836df06713cf9e50bc14162b/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L1003) can return an empty PluginDescription if `component.loadFrom()` or `component->initialize()` has failed. This can be misleading. 

**Proposed Workaround**

I think it would be better to change the internal error handling in `findDescriptionsAndPerform()` in such a way that no plugin description is added to the array if the instantiation of a plugin has failed.

For example:

            PluginDescription desc;
            bool descWasCreated = false;

            {
                ComSmartPtr<Vst::IComponent> component;

                if (component.loadFrom (factory, info.cid))
                {
                    if (component->initialize (vst3HostContext->getFUnknown()) == kResultOk)
                    {
                        auto numInputs  = getNumSingleDirectionChannelsFor (component, true, true);
                        auto numOutputs = getNumSingleDirectionChannelsFor (component, false, true);

                        createPluginDescription (desc, file, companyName, name,
                                                 info, info2.get(), infoW.get(), numInputs, numOutputs);
                        descWasCreated = true;
                        
                        component->terminate();
                    }
                    else
                    {
                        jassertfalse;
                    }
                }
                else
                {
                    jassertfalse;
                }
            }

            if (descWasCreated)
                result = performOnDescription (desc);

**Comment by ed95** [comment]
I've added a check for this in [e86b1a8](https://github.com/WeAreROLI/JUCE/commit/e86b1a8818cc363ee6b2f5f78248daaa373e5d43) - thanks for reporting!
