### ISSUE TITLE
toBehind's behaviour is not consistent

### ISSUE THREAD

**Issue by OlivierSohn** [WeAreROLI/JUCE#628]
https://github.com/WeAreROLI/JUCE/blob/724ae27c71ef809b836df06713cf9e50bc14162b/modules/juce_gui_basics/components/juce_Component.cpp#L944

when doing :
a.toBehind(&b);

if a is initially before b in the child list, after the call it will be just behind b. But if a is initially after b in the child list, after the call, a and b will be swapped, but a will not be just behind b. (one would need to do the call 2 times to be sure that in all cases, a will be just behind b)

Quoting the doc of toBehind:

> Changes this component's z-order so that it's just behind another component

**Comment by julianstorer** [comment]
OMG! The code is fine and has been working correctly for about 15 years!

I can see that it's correct just by looking at it, but just to make you drop this, here's some example code to prove it:

    Component parent, a, b, c;
    parent.addAndMakeVisible (a);
    parent.addAndMakeVisible (b);
    parent.addAndMakeVisible (c);

    a.toBehind (&c);

    DBG (parent.getIndexOfChildComponent (&a));
    DBG (parent.getIndexOfChildComponent (&b));
    DBG (parent.getIndexOfChildComponent (&c));

prints 1, 0, 2 which is exactly what it's supposed to do!

**Comment by OlivierSohn** [comment]
You don't understand what I say, let me write some code to demonstrate the bug

**Comment by julianstorer** [comment]
Yes, please do!

**Comment by OlivierSohn** [comment]
`
Component parent, a, b, c, d;
parent.addAndMakeVisible (a);
parent.addAndMakeVisible (b);
parent.addAndMakeVisible (c);
parent.addAndMakeVisible (d);

d.toBehind (&b);

DBG (parent.getIndexOfChildComponent (&a));
DBG (parent.getIndexOfChildComponent (&b));
DBG (parent.getIndexOfChildComponent (&c));
DBG (parent.getIndexOfChildComponent (&d));
`

This will print 0 3 2 1, so you see that now, d i not "just behind" b, there is c in-between. So it's not doing what the doc says it should do.

**Comment by OlivierSohn** [comment]
Can you reopen the issue please now that you have code to reproduce it?

**Comment by OlivierSohn** [comment]
Do you understand my point?

**Comment by julianstorer** [comment]
I ran that and got

0
2
3
1

So you're probably using code that you've hacked around and broken.

**Comment by OlivierSohn** [comment]
My bad, you're right
