### ISSUE TITLE
Incorrect VST3 host context menu position

### ISSUE THREAD

**Issue by lmdsp** [WeAreROLI/JUCE#639]
I was testing our plug-ins in Waveform 10 Windows with HiDpi enabled and encountered this bug.

As I assume it’s built with Juce, I believe this is the right place to report this.
All other hosts I’ve tested (Cubase, Studio One, FL Studio, Wavelab, Bitwig …) expect to send and receive mouse coordinates in screen / device pixels (unlike macOS which works in device-indepent coordinates) - this is a legacy of win32 I believe.

The result is that the context menu is displayed at the wrong coordinates (Waveform must be applying dpi ratio a second time), as can be seen on the screenshot below (using a vst3 official sample just to check it’s not a bug in our code).

![image](https://user-images.githubusercontent.com/1681470/69822167-f7d09580-1205-11ea-93f1-c2c521256373.png)

**Comment by ed95** [comment]
There have been a number of changes to the plug-in DPI handling code on Windows in [1852310](https://github.com/WeAreROLI/JUCE/commit/18523101be8da6f0dcc1b72501f7876e3a253cbd) and this issue should now be resolved. I'm not sure if these updates have made their way into Waveform but you can verify the fix by opening the JUCE AudioPluginHost project and loading the AGainSimple example.

**Comment by lmdsp** [comment]
Yes thanks I tried in Waveform 11 free the other day and I can confirm it's working fine now.
