### ISSUE TITLE
DragAndDropContainer::dragOperationStarted() always provides 0, 0 for localPosition

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#657]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

- Create a class that inherits from `DragAndDropContainer` and implements `dragOperationStarted()`
- Add a child Component that calls `DragAndDropContainer::startDragging()` on `mouseDrag`

See example code below, which can be used as the MainComponent.h in the standard Projucer GUI app:

```


#pragma once

#include "../JuceLibraryCode/JuceHeader.h"

struct DraggableComp : public Component
{
    void paint(Graphics& g)
    {
        g.fillAll(Colours::red);
    }
    
    void mouseDrag(const MouseEvent& event)
    {
        auto *dragContainer = DragAndDropContainer::findParentDragContainerFor(this);
        dragContainer->startDragging("Test", this);
    }
};


class MainComponent   : public Component, public DragAndDropContainer
{
public:
   
    MainComponent()
    {
        addAndMakeVisible(comp);
        setSize (600, 400);
    }
    ~MainComponent() {}

    void paint (Graphics& g) override
    {
        g.fillAll (getLookAndFeel().findColour (ResizableWindow::backgroundColourId));
    }
    
    void resized() override
    {
        comp.setBounds(getLocalBounds().reduced(100));
    }

private:

    DraggableComp comp;
    
    void dragOperationStarted (const DragAndDropTarget::SourceDetails& details)
    {
        DBG(details.localPosition.toString());
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainComponent)
};
```

  2) the expected behaviour

`localPosition` contains the actual position of the mouse when drag started.

  3) the operating system

macOS Catalina

  4) the architecture (32-bit or 64-bit)
64-bit

  5) a stack trace - if the bug causes a crash
N/A

  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
N/A

  7) which DAW you observed the bug in - if applicable
N/A

**Comment by ed95** [comment]
This should now be fixed in [a313357](https://github.com/WeAreROLI/JUCE/commit/a313357d398f8c333ded577b8557f2e544d0be2a). Thanks for reporting!
