### ISSUE TITLE
Makefile is missing -latomic for JUCE_ARM

### ISSUE THREAD

**Issue by aking7** [WeAreROLI/JUCE#672]
I'm building my app on a Raspberry Pi with the JUCE_ARM flag, but in order to compile I must edit the `Makefile`, adding `-latomic` to the `JUCE_LDFLAGS` section. Without `-latomic` I receive:
```
/usr/bin/ld: build/intermediate/Debug/include_juce_audio_basics_8a4e984a.o: undefined reference to symbol '__atomic_load_8@@LIBATOMIC_1.0'
/usr/bin/ld: //usr/lib/arm-linux-gnueabihf/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Can this be fixed in ProJucer? Otherwise it must be fixed everytime I save my project.

**Comment by McMartin** [comment]
There is an "Extra Linker Flags" field in Projucer, where you can put `-latomic`.

**Comment by umlaeute** [comment]
hmm, using "Extra Linker Flags" doesn't seem right.

if your project doesn't do anything special, than Projucer should fill in the required flags without any hints from the user.

(until Projucer does, "Extra Linker Flags" might of course be a viable workaround to get your projects to compile)

**Comment by tpoole** [comment]
The Makefile created by the Projucer is designed to be compatible with a wide range of compilers; we can't add compiler-specific flags that will break compatibility with others. To customise the build for a specific machine you can do something along the lines of:

`CXX=path/to/compiler LDFLAGS=-latomic make`

**Comment by aking7** [comment]
Thanks @tpoole, that makes sense. I ended up adding `-latomic` to the "Extra linker flags" field in Projucer, which seems like the right way to go.
