### ISSUE TITLE
Error in modules/juce_core/memory/juce_OptionalScopedPointer.h

### ISSUE THREAD

**Issue by syboxez** [WeAreROLI/JUCE#682]
in modules/juce_core/memory/juce_OptionalScopedPointer.h, swapWith() calls for "object" to recursively call swapWith. The problem is that "object" is an std::unique_ptr, which does not have a swapWith() method.

In private:
std::unique_ptr<ObjectType> object;

This leads to compiler errors when trying to use juce_OptionalScopedPointer.h.

Commenting out the line "object.swapWith (other.object);" seems to fix the issue, but I would like a more proper solution, as I don't know if that could lead to issues.

**Comment by ed95** [comment]
`OptionalScopedPointer::swapWith()` now uses `std::swap` since [4b7043b](https://github.com/WeAreROLI/JUCE/commit/4b7043b0cda5478ece6ab06bcb0a88b5c9065690) which should resolve this.
