### ISSUE TITLE
Brackets with no statement in SliderAttachment::Pimpl::setValue

### ISSUE THREAD

**Issue by samparkewolfe** [WeAreROLI/JUCE#684]
Is the contents of these two declarations of setValue in SliderAttachment supposed to be in brackets which don't have a statement?

https://github.com/WeAreROLI/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_audio_processors/utilities/juce_AudioProcessorValueTreeState.cpp#L606

https://github.com/WeAreROLI/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_audio_processors/utilities/juce_AudioProcessorValueTreeState.cpp#L727

**Comment by julianstorer** [comment]
Yes. It's RAII. But please don't post an issue just to ask about something you don't understand - that's what the forum is for!
