### ISSUE TITLE
X11 libraryPath in Demo/extra jucer files

### ISSUE THREAD

**Issue by jwinarske** [WeAreROLI/JUCE#687]
The provided jucer files include libraryPath="/usr/X11R6/lib/" under Linux export.

It should be removed from the Jucer files, as it's not a standard path.

Linux Ubuntu >= 18.0.4 LTS
Yocto Linux variety of targets

**Comment by ed95** [comment]
Thanks, we've removed them in [f7f6dad](https://github.com/WeAreROLI/JUCE/commit/f7f6dad6635a12f68aa526b5f59833678a816f1f). Looks like they were hanging around from an old version and we never got around to removing them.
