### ISSUE TITLE
API-doc search not available / many content like jucePlatformDefs is missing / isPositiveAndBelow not findable

### ISSUE THREAD

**Issue by ffAudio** [WeAreROLI/JUCE#91]
The inheritance diagrams of the doxygen generated api-docs on the website don't work. 
Eventually due to javascript.
The search field is no longer present.

To be observed with 
- firefox on Mac OSX 10.10, 
- Chrome on Mac OSX
- Safari on Mac OSX

**Comment by cWilgar** [comment]
Example:

https://www.juce.com/doc/classAudioProcessorEditor

"The AudioProcessorEditor class should inherit from the Component class, but under the label: "Inheritance Diagram for AudioProcessorEditor" it's empty and the label is not responsive despite being clickable."

**Comment by ffAudio** [comment]
Previously mentioned Dec 2015 on forum:
https://forum.juce.com/t/please-bring-back-the-old-api-documentation/16185

**Comment by ffAudio** [comment]
Possible quickfix:
In doxygen/Doxyfile set
HTML_DYNAMIC_SECTIONS  = NO

That way the inheritance diagrams are shown always, better than never shown...

**Comment by ffAudio** [comment]
The inheritance schemata are fixed now, thanks @tpoole! Makes understanding the structure of the API much easier. 
Only the search is still missing.

**Comment by ffAudio** [comment]
bumping the API doc search...

**Comment by matkatmusic** [comment]
API Doc search is still not available.   Why is this not a priority?

**Comment by ffAudio** [comment]
Another mention in the forum:
https://forum.juce.com/t/api-search/23721

**Comment by ffAudio** [comment]
Defines like JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, jmax, isPositiveAndBelow is not visible on the Web-API-Docs at all.

**Comment by ffAudio** [comment]
Linking some more issues from the forum:
reFX: https://forum.juce.com/t/documentation-urls-and-quick-access/23768/13
Holy_City: https://forum.juce.com/t/documentation-urls-and-quick-access/23768/14

**Comment by matkatmusic** [comment]
Bruh, they just don't care about fixing it right now. They expect users to
generate their own local Doxygen copy from the source or just browse the
source directly.

On Aug 20, 2017 2:00 PM, "Daniel Walz" <notifications@github.com> wrote:

Linking some more issues from the forum:
reFX: https://forum.juce.com/t/documentation-urls-and-quick-access/23768/13
Holy_City: https://forum.juce.com/t/documentation-urls-and-quick-
access/23768/14

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/WeAreROLI/JUCE/issues/91#issuecomment-323601062>, or mute
the thread

**Comment by reFX-Mike** [comment]
I'm prepared to create my own doxygen copy and even implement the search again AND make all that available to the public, but as a starting point I would like the previous doxygen configuration files (the ones right before it was all merged into one giant, useless page), as to not waste any more time on this.

I think how ROLI/JUCE handles their documentation is outrageous and unacceptable. You want developers to use and license your code? Then maybe show us that you give a crap. Right now, almost all forum posts go unanswered.

ROLI still hasn't answered how they want to handle the "pro" support they promised.

**Comment by tpoole** [comment]
We don't care about fixing it? The recent changes are the first steps towards sorting things out...

**Comment by reFX-Mike** [comment]
You broke it in the first place. Was anybody asking for these mega-pages?

How do you expect people to use the text-search in their browser to find anything related to the class their looking for?

Why do you ignore complaints about the theme (colours and font-weights)?

How are any of the recent changes (anything that happened for the 5.0 release and after) an improvement in any way, shape or form?

You broke it. Made it harder to read and now made even the most basic browser-search unusable. If you left it like the last 4.x release, everybody would be much happier.

Here is my first attempt (!) after downloading doxygen and then playing with the css for two hours:

https://juce.refx.com/classSlider.html

All I literally did, was download your doxygen-config file, run it and then add a CSS file via the HTML_EXTRA_STYLESHEET setting. That's literally all I did. Doxygen already features a client-side search (not super-awesome, but better than nothing).

Everything is nicely structured and usable.

**Comment by pizzafilms** [comment]
And oh my god, it's readable!

**Comment by reFX-Mike** [comment]
> And oh my god, it's readable!

Yeah, it's surprising what you can do when you font-weight isn't "light" or "extra-light" and your colours actually have contrast.

**Comment by tpoole** [comment]
There really is no need for such vitriol.

You haven't been ignored - the recent changes to the documentation are, in fact, concrete evidence of the opposite.

Having multiple classes on a single page was a side effect of grouping the classes by module, and, as of a few minutes ago, the old single-class-per-page format has been restored.

The Doxygen search box is now present at the top of each page.

Things like `isPositiveAndBelow` are located at https://juce.com/doc/group__juce__core-maths.

**Comment by ffAudio** [comment]
Thanks so much @tpoole !
This works now perfectly, more than I hoped for.
In the name of the community I want to apologise for all harsh words.
