### ISSUE TITLE
Projucer doesn’t redraw components on mouseEnter / mouseExit

### ISSUE THREAD

**Issue by willricemusic** [WeAreROLI/JUCE#97]
**STR:**
1. Open JuceDemo.jucer in Projucer 4.2.3
2. Build > Enable Compilation
3. Build > Launch Application
4. In the running Demo app, browse to Tabs & Widgets > Buttons [tab]
5. Try hovering over buttons - _note that their mouseOver state is not shown_
6. Try clicking on a button - _note that after clicking, the mouseOver state **is** shown until you click outside the Component_

**Expected Behaviour**

Buttons are drawn with mouseOver state whilst, and only whilst the mouse coordinates are within the Button bounds

**Actual Behaviour** 
- Buttons are not drawn with mouseOver state on mouseEnter
- Once clicked, buttons are drawn with mouseOver state until you subsequently click outside the button bounds

Note\* This affects individual components running in the JIT engine as well as whilst running the whole application inside the Projucer. It does not seem to be limited to Button and its subclasses.

---

OS X 10.11.6 (64-bit)
JUCE / Projucer 4.2.3 (3592d61)
Retina MBP 13" 10,2

**Comment by julianstorer** [comment]
Have you tried focusing on the window that contains the running components? Because it runs in a separate process to the IDE window, it can't receive any mouse events unless you've actually got it focused.

**Comment by willricemusic** [comment]
Hi Jules, at the time of reporting, the component window did indeed have focus. In 5.0.0 this behaviour no longer occurs.

**Comment by julianstorer** [comment]
OK, thanks
