### ISSUE TITLE
FeatureRequest: configurable background colour of AudioDeviceSelectorComponent created by the StandalonePluginHolder

### ISSUE THREAD

**Issue by beschulz** [WeAreROLI/JUCE#98]
It would be nice to be able to configure the background colour of the AudioDeviceSelectorComponent created by the StandalonePluginHolder via the LookAndFell or some other means.

The line with the hard-coded background colour is here:
https://github.com/julianstorer/JUCE/blob/630ab88f8bf11c8389f99a9ffb6daa3a0e891f14/modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h#L198

Thanks for your consideration,
Ben

**Comment by tpoole** [comment]
Fixed: https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h#L261
